/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  GithubComVineethkrishnanVaultctlInternalApplicationAuthExportData,
  ImportRequest,
  ImportResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Export all vaults, items, and folders for the authenticated user. Requires step-up authentication.
 * @summary Export vault data
 */
export type getExportResponse200 = {
  data: GithubComVineethkrishnanVaultctlInternalApplicationAuthExportData
  status: 200
}

export type getExportResponse401 = {
  data: ErrorBody
  status: 401
}

export type getExportResponse403 = {
  data: ErrorBody
  status: 403
}

export type getExportResponseSuccess = (getExportResponse200) & {
  headers: Headers;
};
export type getExportResponseError = (getExportResponse401 | getExportResponse403) & {
  headers: Headers;
};

export type getExportResponse = (getExportResponseSuccess | getExportResponseError)

export const getGetExportUrl = () => {




  return `/export`
}

export const getExport = async ( options?: RequestInit): Promise<getExportResponse> => {

  return apiFetcher<getExportResponse>(getGetExportUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExportQueryKey = () => {
    return [
    `/export`
    ] as const;
    }


export const getGetExportQueryOptions = <TData = Awaited<ReturnType<typeof getExport>>, TError = ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExportQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExport>>> = ({ signal }) => getExport({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExportQueryResult = NonNullable<Awaited<ReturnType<typeof getExport>>>
export type GetExportQueryError = ErrorBody


export function useGetExport<TData = Awaited<ReturnType<typeof getExport>>, TError = ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExport>>,
          TError,
          Awaited<ReturnType<typeof getExport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExport<TData = Awaited<ReturnType<typeof getExport>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExport>>,
          TError,
          Awaited<ReturnType<typeof getExport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExport<TData = Awaited<ReturnType<typeof getExport>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export vault data
 */

export function useGetExport<TData = Awaited<ReturnType<typeof getExport>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExportQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Batch-import encrypted items into a vault. Client performs format conversion and encryption.
 * @summary Import vault items
 */
export type postImportResponse200 = {
  data: ImportResponse
  status: 200
}

export type postImportResponse400 = {
  data: ErrorBody
  status: 400
}

export type postImportResponse401 = {
  data: ErrorBody
  status: 401
}

export type postImportResponse404 = {
  data: ErrorBody
  status: 404
}

export type postImportResponseSuccess = (postImportResponse200) & {
  headers: Headers;
};
export type postImportResponseError = (postImportResponse400 | postImportResponse401 | postImportResponse404) & {
  headers: Headers;
};

export type postImportResponse = (postImportResponseSuccess | postImportResponseError)

export const getPostImportUrl = () => {




  return `/import`
}

export const postImport = async (importRequest: ImportRequest, options?: RequestInit): Promise<postImportResponse> => {

  return apiFetcher<postImportResponse>(getPostImportUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      importRequest,)
  }
);}




export const getPostImportMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postImport>>, TError,{data: ImportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postImport>>, TError,{data: ImportRequest}, TContext> => {

const mutationKey = ['postImport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postImport>>, {data: ImportRequest}> = (props) => {
          const {data} = props ?? {};

          return  postImport(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostImportMutationResult = NonNullable<Awaited<ReturnType<typeof postImport>>>
    export type PostImportMutationBody = ImportRequest
    export type PostImportMutationError = ErrorBody

    /**
 * @summary Import vault items
 */
export const usePostImport = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postImport>>, TError,{data: ImportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postImport>>,
        TError,
        {data: ImportRequest},
        TContext
      > => {
      return useMutation(getPostImportMutationOptions(options), queryClient);
    }
