/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOrgRequest,
  ErrorBody,
  OrgMemberResponse,
  OrgResponse,
  PublicKeyResponse,
  RemoveOrgMemberResponse,
  UpdateMemberRoleRequest
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Admin creates a new organization
 * @summary Create organization
 */
export type postOrgsResponse201 = {
  data: OrgResponse
  status: 201
}

export type postOrgsResponse400 = {
  data: ErrorBody
  status: 400
}

export type postOrgsResponse401 = {
  data: ErrorBody
  status: 401
}

export type postOrgsResponse403 = {
  data: ErrorBody
  status: 403
}

export type postOrgsResponseSuccess = (postOrgsResponse201) & {
  headers: Headers;
};
export type postOrgsResponseError = (postOrgsResponse400 | postOrgsResponse401 | postOrgsResponse403) & {
  headers: Headers;
};

export type postOrgsResponse = (postOrgsResponseSuccess | postOrgsResponseError)

export const getPostOrgsUrl = () => {




  return `/orgs`
}

export const postOrgs = async (createOrgRequest: CreateOrgRequest, options?: RequestInit): Promise<postOrgsResponse> => {

  return apiFetcher<postOrgsResponse>(getPostOrgsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrgRequest,)
  }
);}




export const getPostOrgsMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrgs>>, TError,{data: CreateOrgRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postOrgs>>, TError,{data: CreateOrgRequest}, TContext> => {

const mutationKey = ['postOrgs'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrgs>>, {data: CreateOrgRequest}> = (props) => {
          const {data} = props ?? {};

          return  postOrgs(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostOrgsMutationResult = NonNullable<Awaited<ReturnType<typeof postOrgs>>>
    export type PostOrgsMutationBody = CreateOrgRequest
    export type PostOrgsMutationError = ErrorBody

    /**
 * @summary Create organization
 */
export const usePostOrgs = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrgs>>, TError,{data: CreateOrgRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postOrgs>>,
        TError,
        {data: CreateOrgRequest},
        TContext
      > => {
      return useMutation(getPostOrgsMutationOptions(options), queryClient);
    }
    /**
 * List all members of an organization
 * @summary List org members
 */
export type getOrgsIdMembersResponse200 = {
  data: OrgMemberResponse[]
  status: 200
}

export type getOrgsIdMembersResponse401 = {
  data: ErrorBody
  status: 401
}

export type getOrgsIdMembersResponse404 = {
  data: ErrorBody
  status: 404
}

export type getOrgsIdMembersResponseSuccess = (getOrgsIdMembersResponse200) & {
  headers: Headers;
};
export type getOrgsIdMembersResponseError = (getOrgsIdMembersResponse401 | getOrgsIdMembersResponse404) & {
  headers: Headers;
};

export type getOrgsIdMembersResponse = (getOrgsIdMembersResponseSuccess | getOrgsIdMembersResponseError)

export const getGetOrgsIdMembersUrl = (id: string,) => {




  return `/orgs/${id}/members`
}

export const getOrgsIdMembers = async (id: string, options?: RequestInit): Promise<getOrgsIdMembersResponse> => {

  return apiFetcher<getOrgsIdMembersResponse>(getGetOrgsIdMembersUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrgsIdMembersQueryKey = (id: string,) => {
    return [
    `/orgs/${id}/members`
    ] as const;
    }


export const getGetOrgsIdMembersQueryOptions = <TData = Awaited<ReturnType<typeof getOrgsIdMembers>>, TError = ErrorBody>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrgsIdMembersQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrgsIdMembers>>> = ({ signal }) => getOrgsIdMembers(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrgsIdMembersQueryResult = NonNullable<Awaited<ReturnType<typeof getOrgsIdMembers>>>
export type GetOrgsIdMembersQueryError = ErrorBody


export function useGetOrgsIdMembers<TData = Awaited<ReturnType<typeof getOrgsIdMembers>>, TError = ErrorBody>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getOrgsIdMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgsIdMembers<TData = Awaited<ReturnType<typeof getOrgsIdMembers>>, TError = ErrorBody>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getOrgsIdMembers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgsIdMembers<TData = Awaited<ReturnType<typeof getOrgsIdMembers>>, TError = ErrorBody>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List org members
 */

export function useGetOrgsIdMembers<TData = Awaited<ReturnType<typeof getOrgsIdMembers>>, TError = ErrorBody>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembers>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrgsIdMembersQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a member's role within an organization
 * @summary Update member role
 */
export type putOrgsIdMembersUserIdResponse204 = {
  data: void
  status: 204
}

export type putOrgsIdMembersUserIdResponse400 = {
  data: ErrorBody
  status: 400
}

export type putOrgsIdMembersUserIdResponse401 = {
  data: ErrorBody
  status: 401
}

export type putOrgsIdMembersUserIdResponse403 = {
  data: ErrorBody
  status: 403
}

export type putOrgsIdMembersUserIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type putOrgsIdMembersUserIdResponseSuccess = (putOrgsIdMembersUserIdResponse204) & {
  headers: Headers;
};
export type putOrgsIdMembersUserIdResponseError = (putOrgsIdMembersUserIdResponse400 | putOrgsIdMembersUserIdResponse401 | putOrgsIdMembersUserIdResponse403 | putOrgsIdMembersUserIdResponse404) & {
  headers: Headers;
};

export type putOrgsIdMembersUserIdResponse = (putOrgsIdMembersUserIdResponseSuccess | putOrgsIdMembersUserIdResponseError)

export const getPutOrgsIdMembersUserIdUrl = (id: string,
    userId: string,) => {




  return `/orgs/${id}/members/${userId}`
}

export const putOrgsIdMembersUserId = async (id: string,
    userId: string,
    updateMemberRoleRequest: UpdateMemberRoleRequest, options?: RequestInit): Promise<putOrgsIdMembersUserIdResponse> => {

  return apiFetcher<putOrgsIdMembersUserIdResponse>(getPutOrgsIdMembersUserIdUrl(id,userId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateMemberRoleRequest,)
  }
);}




export const getPutOrgsIdMembersUserIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putOrgsIdMembersUserId>>, TError,{id: string;userId: string;data: UpdateMemberRoleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putOrgsIdMembersUserId>>, TError,{id: string;userId: string;data: UpdateMemberRoleRequest}, TContext> => {

const mutationKey = ['putOrgsIdMembersUserId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putOrgsIdMembersUserId>>, {id: string;userId: string;data: UpdateMemberRoleRequest}> = (props) => {
          const {id,userId,data} = props ?? {};

          return  putOrgsIdMembersUserId(id,userId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutOrgsIdMembersUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof putOrgsIdMembersUserId>>>
    export type PutOrgsIdMembersUserIdMutationBody = UpdateMemberRoleRequest
    export type PutOrgsIdMembersUserIdMutationError = ErrorBody

    /**
 * @summary Update member role
 */
export const usePutOrgsIdMembersUserId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putOrgsIdMembersUserId>>, TError,{id: string;userId: string;data: UpdateMemberRoleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putOrgsIdMembersUserId>>,
        TError,
        {id: string;userId: string;data: UpdateMemberRoleRequest},
        TContext
      > => {
      return useMutation(getPutOrgsIdMembersUserIdMutationOptions(options), queryClient);
    }
    /**
 * Remove a user from the organization. Cascades into shared-vault memberships and triggers an unconditional client-driven rekey of every affected vault.
 * @summary Remove org member
 */
export type deleteOrgsIdMembersUserIdResponse200 = {
  data: RemoveOrgMemberResponse
  status: 200
}

export type deleteOrgsIdMembersUserIdResponse400 = {
  data: ErrorBody
  status: 400
}

export type deleteOrgsIdMembersUserIdResponse401 = {
  data: ErrorBody
  status: 401
}

export type deleteOrgsIdMembersUserIdResponse403 = {
  data: ErrorBody
  status: 403
}

export type deleteOrgsIdMembersUserIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteOrgsIdMembersUserIdResponseSuccess = (deleteOrgsIdMembersUserIdResponse200) & {
  headers: Headers;
};
export type deleteOrgsIdMembersUserIdResponseError = (deleteOrgsIdMembersUserIdResponse400 | deleteOrgsIdMembersUserIdResponse401 | deleteOrgsIdMembersUserIdResponse403 | deleteOrgsIdMembersUserIdResponse404) & {
  headers: Headers;
};

export type deleteOrgsIdMembersUserIdResponse = (deleteOrgsIdMembersUserIdResponseSuccess | deleteOrgsIdMembersUserIdResponseError)

export const getDeleteOrgsIdMembersUserIdUrl = (id: string,
    userId: string,) => {




  return `/orgs/${id}/members/${userId}`
}

export const deleteOrgsIdMembersUserId = async (id: string,
    userId: string, options?: RequestInit): Promise<deleteOrgsIdMembersUserIdResponse> => {

  return apiFetcher<deleteOrgsIdMembersUserIdResponse>(getDeleteOrgsIdMembersUserIdUrl(id,userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteOrgsIdMembersUserIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrgsIdMembersUserId>>, TError,{id: string;userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrgsIdMembersUserId>>, TError,{id: string;userId: string}, TContext> => {

const mutationKey = ['deleteOrgsIdMembersUserId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrgsIdMembersUserId>>, {id: string;userId: string}> = (props) => {
          const {id,userId} = props ?? {};

          return  deleteOrgsIdMembersUserId(id,userId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrgsIdMembersUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrgsIdMembersUserId>>>

    export type DeleteOrgsIdMembersUserIdMutationError = ErrorBody

    /**
 * @summary Remove org member
 */
export const useDeleteOrgsIdMembersUserId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrgsIdMembersUserId>>, TError,{id: string;userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrgsIdMembersUserId>>,
        TError,
        {id: string;userId: string},
        TContext
      > => {
      return useMutation(getDeleteOrgsIdMembersUserIdMutationOptions(options), queryClient);
    }
    /**
 * Returns a member's public keys for encrypting shared vault keys
 * @summary Get member public key
 */
export type getOrgsIdMembersUserIdPubkeyResponse200 = {
  data: PublicKeyResponse
  status: 200
}

export type getOrgsIdMembersUserIdPubkeyResponse401 = {
  data: ErrorBody
  status: 401
}

export type getOrgsIdMembersUserIdPubkeyResponse404 = {
  data: ErrorBody
  status: 404
}

export type getOrgsIdMembersUserIdPubkeyResponseSuccess = (getOrgsIdMembersUserIdPubkeyResponse200) & {
  headers: Headers;
};
export type getOrgsIdMembersUserIdPubkeyResponseError = (getOrgsIdMembersUserIdPubkeyResponse401 | getOrgsIdMembersUserIdPubkeyResponse404) & {
  headers: Headers;
};

export type getOrgsIdMembersUserIdPubkeyResponse = (getOrgsIdMembersUserIdPubkeyResponseSuccess | getOrgsIdMembersUserIdPubkeyResponseError)

export const getGetOrgsIdMembersUserIdPubkeyUrl = (id: string,
    userId: string,) => {




  return `/orgs/${id}/members/${userId}/pubkey`
}

export const getOrgsIdMembersUserIdPubkey = async (id: string,
    userId: string, options?: RequestInit): Promise<getOrgsIdMembersUserIdPubkeyResponse> => {

  return apiFetcher<getOrgsIdMembersUserIdPubkeyResponse>(getGetOrgsIdMembersUserIdPubkeyUrl(id,userId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrgsIdMembersUserIdPubkeyQueryKey = (id: string,
    userId: string,) => {
    return [
    `/orgs/${id}/members/${userId}/pubkey`
    ] as const;
    }


export const getGetOrgsIdMembersUserIdPubkeyQueryOptions = <TData = Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError = ErrorBody>(id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrgsIdMembersUserIdPubkeyQueryKey(id,userId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>> = ({ signal }) => getOrgsIdMembersUserIdPubkey(id,userId, { signal });





   return  { queryKey, queryFn, enabled: !!(id && userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrgsIdMembersUserIdPubkeyQueryResult = NonNullable<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>>
export type GetOrgsIdMembersUserIdPubkeyQueryError = ErrorBody


export function useGetOrgsIdMembersUserIdPubkey<TData = Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError = ErrorBody>(
 id: string,
    userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>,
          TError,
          Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgsIdMembersUserIdPubkey<TData = Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError = ErrorBody>(
 id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>,
          TError,
          Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgsIdMembersUserIdPubkey<TData = Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError = ErrorBody>(
 id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get member public key
 */

export function useGetOrgsIdMembersUserIdPubkey<TData = Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError = ErrorBody>(
 id: string,
    userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdMembersUserIdPubkey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrgsIdMembersUserIdPubkeyQueryOptions(id,userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




