// SPDX-License-Identifier: AGPL-3.0-or-later

const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SERVICE_NAME = ".autofill.VaultAutofillService";
const RES_FILE = "autofill_service.xml";

// The service needs a res/xml descriptor pointing at its settings activity.
// Written from the plugin so `expo prebuild --clean` reproduces it.
const RES_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<autofill-service xmlns:android="http://schemas.android.com/apk/res/android"
    android:settingsActivity="com.vaultctl.app.MainActivity" />
`;

function addAutofillService(androidManifest, packageName) {
  const application =
    AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);

  application.service = application.service ?? [];
  const already = application.service.some(
    (service) => service.$?.["android:name"] === SERVICE_NAME,
  );
  if (already) return androidManifest;

  application.service.push({
    $: {
      "android:name": SERVICE_NAME,
      "android:label": "vaultctl",
      "android:permission": "android.permission.BIND_AUTOFILL_SERVICE",
      "android:exported": "true",
    },
    "meta-data": [
      {
        $: {
          "android:name": "android.autofill",
          "android:resource": `@xml/${RES_FILE.replace(".xml", "")}`,
        },
      },
    ],
    "intent-filter": [
      {
        action: [{ $: { "android:name": "android.service.autofill.AutofillService" } }],
      },
    ],
  });

  return androidManifest;
}

/**
 * Declares the Android autofill service.
 *
 * mobile/android is gitignored and regenerated by `expo prebuild`, so any
 * hand-edit of the manifest is erased. Everything native has to arrive through
 * a plugin like this one.
 *
 * NOTE: this declares the service only. The Kotlin implementation it names does
 * not exist yet, so do not enable the plugin for a release build until it does.
 */
module.exports = function withAndroidAutofill(config) {
  const withManifest = withAndroidManifest(config, (mod) => {
    mod.modResults = addAutofillService(mod.modResults, mod.android?.package);
    return mod;
  });

  return withDangerousMod(withManifest, [
    "android",
    (mod) => {
      const xmlDir = path.join(
        mod.modRequest.platformProjectRoot,
        "app/src/main/res/xml",
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, RES_FILE), RES_CONTENT, "utf8");
      return mod;
    },
  ]);
};
