// SPDX-License-Identifier: AGPL-3.0-or-later

const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SERVICE_NAME = ".autofill.VaultAutofillService";
const SOURCE_DIR = path.join(__dirname, "android");

// The package the checked-in Kotlin template is written against. Rewritten to
// whatever android.package resolves to, so the two cannot drift.
const TEMPLATE_PACKAGE = "com.vaultctl.app";

// The service needs a res/xml descriptor pointing at its settings activity.
// Written from the plugin so `expo prebuild --clean` reproduces it.
const RES_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<autofill-service xmlns:android="http://schemas.android.com/apk/res/android"
    android:settingsActivity="com.vaultctl.app.MainActivity" />
`;

function addAutofillService(androidManifest) {
  const application =
    AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);

  application.service = application.service ?? [];
  const already = application.service.some(
    (service) => service.$?.["android:name"] === SERVICE_NAME,
  );
  if (already) return androidManifest;

  application.service.push({
    $: {
      "android:name": SERVICE_NAME,
      "android:label": "vaultctl",
      "android:permission": "android.permission.BIND_AUTOFILL_SERVICE",
      "android:exported": "true",
    },
    "meta-data": [
      {
        $: {
          "android:name": "android.autofill",
          "android:resource": "@xml/autofill_service",
        },
      },
    ],
    "intent-filter": [
      {
        action: [{ $: { "android:name": "android.service.autofill.AutofillService" } }],
      },
    ],
  });

  return androidManifest;
}

function writeFile(targetPath, contents) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, contents, "utf8");
}

function copyTemplate(name, targetPath, transform) {
  const contents = fs.readFileSync(path.join(SOURCE_DIR, name), "utf8");
  writeFile(targetPath, transform ? transform(contents) : contents);
}

function writeNativeSources(projectRoot, packageName) {
  const main = path.join(projectRoot, "app/src/main");

  writeFile(path.join(main, "res/xml/autofill_service.xml"), RES_CONTENT);
  copyTemplate("autofill_unlock.xml", path.join(main, "res/layout/autofill_unlock.xml"));
  copyTemplate("autofill_strings.xml", path.join(main, "res/values/autofill_strings.xml"));

  const packageDir = path.join(main, "java", ...packageName.split("."), "autofill");
  copyTemplate(
    "VaultAutofillService.kt",
    path.join(packageDir, "VaultAutofillService.kt"),
    (source) => source.split(TEMPLATE_PACKAGE).join(packageName),
  );
}

/**
 * Declares the Android autofill service and emits its Kotlin implementation.
 *
 * mobile/android is gitignored and regenerated by `expo prebuild`, so any
 * hand-edit of the generated project is erased. Everything native has to
 * arrive through a plugin like this one, sources included; the reviewable
 * copies live in mobile/plugins/android/.
 */
module.exports = function withAndroidAutofill(config) {
  const withManifest = withAndroidManifest(config, (mod) => {
    mod.modResults = addAutofillService(mod.modResults);
    return mod;
  });

  return withDangerousMod(withManifest, [
    "android",
    (mod) => {
      const packageName = mod.android?.package;
      if (!packageName) {
        throw new Error(
          "withAndroidAutofill: android.package must be set before the autofill service can be generated.",
        );
      }
      writeNativeSources(mod.modRequest.platformProjectRoot, packageName);
      return mod;
    },
  ]);
};
