// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Canonical Argon2id interop vectors, embedded for runtime bundling.
 *
 * Byte-identical to testdata/crypto/argon2_fixtures.json (generated by the web
 * hash-wasm suite, verified against Go in clientcrypto/interop_test.go). The
 * jest guard __tests__/crypto/argon2-vector.test.ts asserts this copy never
 * drifts from that fixture.
 *
 * This module is intentionally free of native imports so it can be loaded under
 * jest; the native self-check lives in verifyArgon2id.ts.
 */

export interface Argon2idVector {
  password: string;
  salt_b64: string;
  iterations: number;
  memory_kb: number;
  parallelism: number;
  master_key_b64: string;
}

export const ARGON2_VECTORS: readonly Argon2idVector[] = [
  {
    password: 'correct horse battery staple',
    salt_b64: 'EREREREREREREREREREREQ==',
    iterations: 3,
    memory_kb: 65536,
    parallelism: 4,
    master_key_b64: '2qIlRDJYs8JxMLmHI3jdYWckyAcmE/uUg0JbgkY0vDA=',
  },
  {
    password: 'hunter2',
    salt_b64: 'KioqKioqKioqKioqKioqKg==',
    iterations: 1,
    memory_kb: 19456,
    parallelism: 1,
    master_key_b64: 'pC0KUonnk94L1vSdnwGPz+KC0jjOAtGc0RYzWbZTtG8=',
  },
];
