/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  FolderCreateRequest,
  FolderResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * List all folders in the specified vault
 * @summary List folders
 */
export type getVaultsVaultIdFoldersResponse200 = {
  data: FolderResponse[]
  status: 200
}

export type getVaultsVaultIdFoldersResponse404 = {
  data: ErrorBody
  status: 404
}

export type getVaultsVaultIdFoldersResponseSuccess = (getVaultsVaultIdFoldersResponse200) & {
  headers: Headers;
};
export type getVaultsVaultIdFoldersResponseError = (getVaultsVaultIdFoldersResponse404) & {
  headers: Headers;
};

export type getVaultsVaultIdFoldersResponse = (getVaultsVaultIdFoldersResponseSuccess | getVaultsVaultIdFoldersResponseError)

export const getGetVaultsVaultIdFoldersUrl = (vaultId: string,) => {




  return `/vaults/${vaultId}/folders`
}

export const getVaultsVaultIdFolders = async (vaultId: string, options?: RequestInit): Promise<getVaultsVaultIdFoldersResponse> => {

  return apiFetcher<getVaultsVaultIdFoldersResponse>(getGetVaultsVaultIdFoldersUrl(vaultId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVaultsVaultIdFoldersQueryKey = (vaultId: string,) => {
    return [
    `/vaults/${vaultId}/folders`
    ] as const;
    }


export const getGetVaultsVaultIdFoldersQueryOptions = <TData = Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError = ErrorBody>(vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVaultsVaultIdFoldersQueryKey(vaultId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>> = ({ signal }) => getVaultsVaultIdFolders(vaultId, { signal });





   return  { queryKey, queryFn, enabled: !!(vaultId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVaultsVaultIdFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>>
export type GetVaultsVaultIdFoldersQueryError = ErrorBody


export function useGetVaultsVaultIdFolders<TData = Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError = ErrorBody>(
 vaultId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdFolders>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdFolders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdFolders<TData = Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError = ErrorBody>(
 vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdFolders>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdFolders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdFolders<TData = Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError = ErrorBody>(
 vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List folders
 */

export function useGetVaultsVaultIdFolders<TData = Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError = ErrorBody>(
 vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdFolders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVaultsVaultIdFoldersQueryOptions(vaultId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new encrypted folder in the specified vault
 * @summary Create folder
 */
export type postVaultsVaultIdFoldersResponse201 = {
  data: FolderResponse
  status: 201
}

export type postVaultsVaultIdFoldersResponse400 = {
  data: ErrorBody
  status: 400
}

export type postVaultsVaultIdFoldersResponse404 = {
  data: ErrorBody
  status: 404
}

export type postVaultsVaultIdFoldersResponseSuccess = (postVaultsVaultIdFoldersResponse201) & {
  headers: Headers;
};
export type postVaultsVaultIdFoldersResponseError = (postVaultsVaultIdFoldersResponse400 | postVaultsVaultIdFoldersResponse404) & {
  headers: Headers;
};

export type postVaultsVaultIdFoldersResponse = (postVaultsVaultIdFoldersResponseSuccess | postVaultsVaultIdFoldersResponseError)

export const getPostVaultsVaultIdFoldersUrl = (vaultId: string,) => {




  return `/vaults/${vaultId}/folders`
}

export const postVaultsVaultIdFolders = async (vaultId: string,
    folderCreateRequest: FolderCreateRequest, options?: RequestInit): Promise<postVaultsVaultIdFoldersResponse> => {

  return apiFetcher<postVaultsVaultIdFoldersResponse>(getPostVaultsVaultIdFoldersUrl(vaultId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      folderCreateRequest,)
  }
);}




export const getPostVaultsVaultIdFoldersMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdFolders>>, TError,{vaultId: string;data: FolderCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdFolders>>, TError,{vaultId: string;data: FolderCreateRequest}, TContext> => {

const mutationKey = ['postVaultsVaultIdFolders'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postVaultsVaultIdFolders>>, {vaultId: string;data: FolderCreateRequest}> = (props) => {
          const {vaultId,data} = props ?? {};

          return  postVaultsVaultIdFolders(vaultId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostVaultsVaultIdFoldersMutationResult = NonNullable<Awaited<ReturnType<typeof postVaultsVaultIdFolders>>>
    export type PostVaultsVaultIdFoldersMutationBody = FolderCreateRequest
    export type PostVaultsVaultIdFoldersMutationError = ErrorBody

    /**
 * @summary Create folder
 */
export const usePostVaultsVaultIdFolders = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdFolders>>, TError,{vaultId: string;data: FolderCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postVaultsVaultIdFolders>>,
        TError,
        {vaultId: string;data: FolderCreateRequest},
        TContext
      > => {
      return useMutation(getPostVaultsVaultIdFoldersMutationOptions(options), queryClient);
    }
    /**
 * Update the encrypted name of a folder
 * @summary Rename folder
 */
export type putVaultsVaultIdFoldersFolderIdResponse200 = {
  data: FolderResponse
  status: 200
}

export type putVaultsVaultIdFoldersFolderIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type putVaultsVaultIdFoldersFolderIdResponseSuccess = (putVaultsVaultIdFoldersFolderIdResponse200) & {
  headers: Headers;
};
export type putVaultsVaultIdFoldersFolderIdResponseError = (putVaultsVaultIdFoldersFolderIdResponse404) & {
  headers: Headers;
};

export type putVaultsVaultIdFoldersFolderIdResponse = (putVaultsVaultIdFoldersFolderIdResponseSuccess | putVaultsVaultIdFoldersFolderIdResponseError)

export const getPutVaultsVaultIdFoldersFolderIdUrl = (vaultId: string,
    folderId: string,) => {




  return `/vaults/${vaultId}/folders/${folderId}`
}

export const putVaultsVaultIdFoldersFolderId = async (vaultId: string,
    folderId: string,
    folderCreateRequest: FolderCreateRequest, options?: RequestInit): Promise<putVaultsVaultIdFoldersFolderIdResponse> => {

  return apiFetcher<putVaultsVaultIdFoldersFolderIdResponse>(getPutVaultsVaultIdFoldersFolderIdUrl(vaultId,folderId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      folderCreateRequest,)
  }
);}




export const getPutVaultsVaultIdFoldersFolderIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdFoldersFolderId>>, TError,{vaultId: string;folderId: string;data: FolderCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdFoldersFolderId>>, TError,{vaultId: string;folderId: string;data: FolderCreateRequest}, TContext> => {

const mutationKey = ['putVaultsVaultIdFoldersFolderId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putVaultsVaultIdFoldersFolderId>>, {vaultId: string;folderId: string;data: FolderCreateRequest}> = (props) => {
          const {vaultId,folderId,data} = props ?? {};

          return  putVaultsVaultIdFoldersFolderId(vaultId,folderId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutVaultsVaultIdFoldersFolderIdMutationResult = NonNullable<Awaited<ReturnType<typeof putVaultsVaultIdFoldersFolderId>>>
    export type PutVaultsVaultIdFoldersFolderIdMutationBody = FolderCreateRequest
    export type PutVaultsVaultIdFoldersFolderIdMutationError = ErrorBody

    /**
 * @summary Rename folder
 */
export const usePutVaultsVaultIdFoldersFolderId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdFoldersFolderId>>, TError,{vaultId: string;folderId: string;data: FolderCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putVaultsVaultIdFoldersFolderId>>,
        TError,
        {vaultId: string;folderId: string;data: FolderCreateRequest},
        TContext
      > => {
      return useMutation(getPutVaultsVaultIdFoldersFolderIdMutationOptions(options), queryClient);
    }
    /**
 * Delete a folder (items in the folder are not deleted, just unlinked)
 * @summary Delete folder
 */
export type deleteVaultsVaultIdFoldersFolderIdResponse204 = {
  data: void
  status: 204
}

export type deleteVaultsVaultIdFoldersFolderIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteVaultsVaultIdFoldersFolderIdResponseSuccess = (deleteVaultsVaultIdFoldersFolderIdResponse204) & {
  headers: Headers;
};
export type deleteVaultsVaultIdFoldersFolderIdResponseError = (deleteVaultsVaultIdFoldersFolderIdResponse404) & {
  headers: Headers;
};

export type deleteVaultsVaultIdFoldersFolderIdResponse = (deleteVaultsVaultIdFoldersFolderIdResponseSuccess | deleteVaultsVaultIdFoldersFolderIdResponseError)

export const getDeleteVaultsVaultIdFoldersFolderIdUrl = (vaultId: string,
    folderId: string,) => {




  return `/vaults/${vaultId}/folders/${folderId}`
}

export const deleteVaultsVaultIdFoldersFolderId = async (vaultId: string,
    folderId: string, options?: RequestInit): Promise<deleteVaultsVaultIdFoldersFolderIdResponse> => {

  return apiFetcher<deleteVaultsVaultIdFoldersFolderIdResponse>(getDeleteVaultsVaultIdFoldersFolderIdUrl(vaultId,folderId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteVaultsVaultIdFoldersFolderIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdFoldersFolderId>>, TError,{vaultId: string;folderId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdFoldersFolderId>>, TError,{vaultId: string;folderId: string}, TContext> => {

const mutationKey = ['deleteVaultsVaultIdFoldersFolderId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVaultsVaultIdFoldersFolderId>>, {vaultId: string;folderId: string}> = (props) => {
          const {vaultId,folderId} = props ?? {};

          return  deleteVaultsVaultIdFoldersFolderId(vaultId,folderId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteVaultsVaultIdFoldersFolderIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVaultsVaultIdFoldersFolderId>>>

    export type DeleteVaultsVaultIdFoldersFolderIdMutationError = ErrorBody

    /**
 * @summary Delete folder
 */
export const useDeleteVaultsVaultIdFoldersFolderId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdFoldersFolderId>>, TError,{vaultId: string;folderId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVaultsVaultIdFoldersFolderId>>,
        TError,
        {vaultId: string;folderId: string},
        TContext
      > => {
      return useMutation(getDeleteVaultsVaultIdFoldersFolderIdMutationOptions(options), queryClient);
    }
