// SPDX-License-Identifier: AGPL-3.0-or-later

import { useState, useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import { Download, QrCode } from "lucide-react";
import { drawQRToCanvas } from "@/components/ui/QRCode";

interface RecoveryKitDownloadProps {
  recoveryKey: string;
}

/**
 * RecoveryKitDownload - offers a printable HTML download and a scannable QR
 * code of the recovery key. Uses the in-house QR encoder (no external deps).
 */
export function RecoveryKitDownload({ recoveryKey }: RecoveryKitDownloadProps) {
  const { t } = useTranslation("security");
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [qrReady, setQrReady] = useState(false);

  useEffect(() => {
    if (canvasRef.current) {
      setQrReady(drawQRToCanvas(canvasRef.current, recoveryKey, { size: 220, level: "M" }));
    }
  }, [recoveryKey]);

  function handleDownloadPDF() {
    const qrDataUrl = canvasRef.current?.toDataURL("image/png") ?? "";
    const html = buildRecoveryHTML(recoveryKey, qrDataUrl);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "vaultctl-recovery-kit.html";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-3">
      {/* QR code */}
      <div className="flex items-center gap-2">
        <QrCode className="h-4 w-4 text-muted-foreground" />
        <span className="text-sm font-medium">{t("recoveryDownload.qrCode")}</span>
      </div>
      <div className="flex justify-center rounded-md border border-border bg-white p-4">
        <canvas ref={canvasRef} width={200} height={200} />
      </div>

      {/* Download button */}
      <button
        onClick={handleDownloadPDF}
        disabled={!qrReady}
        className="flex w-full items-center justify-center gap-2 rounded-md border border-input px-4 py-2 text-sm font-medium text-foreground hover:bg-muted disabled:opacity-50"
      >
        <Download className="h-4 w-4" />
        {t("recoveryDownload.download")}
      </button>
      <p className="text-xs text-muted-foreground text-center">
        {t("recoveryDownload.hint")}
      </p>
    </div>
  );
}

function buildRecoveryHTML(key: string, qrDataUrl: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>VaultCTL Recovery Kit</title>
<style>
  body { font-family: -apple-system, system-ui, sans-serif; max-width: 600px; margin: 40px auto; padding: 20px; }
  h1 { color: #111; font-size: 24px; }
  .key { font-family: monospace; font-size: 14px; background: #f5f5f5; border: 1px solid #ddd; padding: 16px; border-radius: 8px; word-break: break-all; margin: 16px 0; }
  .qr { text-align: center; margin: 24px 0; }
  .qr img { width: 200px; height: 200px; image-rendering: pixelated; }
  .warning { background: #fff3cd; border: 1px solid #ffc107; padding: 12px; border-radius: 8px; font-size: 13px; margin-top: 24px; }
  .footer { margin-top: 32px; font-size: 11px; color: #666; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>
<h1>VaultCTL Recovery Kit</h1>
<p>This recovery key is the <strong>only way</strong> to recover your vault if you forget your master password. Store this document in a safe, offline location.</p>

<div class="key">${key}</div>

${qrDataUrl ? `<div class="qr"><img src="${qrDataUrl}" alt="Recovery key QR code" /></div>` : ""}

<div class="warning">
<strong>Warning:</strong> Anyone with this key can access your vault. Do not share it. Do not store it digitally unless encrypted. Print this page and lock it away.
</div>

<div class="footer">
Generated by vaultctl on ${new Date().toISOString().slice(0, 10)}. This file contains sensitive material.
</div>
</body>
</html>`;
}
