/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  RekeyVaultRequest,
  RemoveMemberResponse,
  ShareVaultRequest
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Add a new member to a shared vault with an encrypted vault key
 * @summary Share vault
 */
export type postVaultsVaultIdMembersResponse204 = {
  data: void
  status: 204
}

export type postVaultsVaultIdMembersResponse400 = {
  data: ErrorBody
  status: 400
}

export type postVaultsVaultIdMembersResponse404 = {
  data: ErrorBody
  status: 404
}

export type postVaultsVaultIdMembersResponseSuccess = (postVaultsVaultIdMembersResponse204) & {
  headers: Headers;
};
export type postVaultsVaultIdMembersResponseError = (postVaultsVaultIdMembersResponse400 | postVaultsVaultIdMembersResponse404) & {
  headers: Headers;
};

export type postVaultsVaultIdMembersResponse = (postVaultsVaultIdMembersResponseSuccess | postVaultsVaultIdMembersResponseError)

export const getPostVaultsVaultIdMembersUrl = (vaultId: string,) => {




  return `/vaults/${vaultId}/members`
}

export const postVaultsVaultIdMembers = async (vaultId: string,
    shareVaultRequest: ShareVaultRequest, options?: RequestInit): Promise<postVaultsVaultIdMembersResponse> => {

  return apiFetcher<postVaultsVaultIdMembersResponse>(getPostVaultsVaultIdMembersUrl(vaultId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      shareVaultRequest,)
  }
);}




export const getPostVaultsVaultIdMembersMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdMembers>>, TError,{vaultId: string;data: ShareVaultRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdMembers>>, TError,{vaultId: string;data: ShareVaultRequest}, TContext> => {

const mutationKey = ['postVaultsVaultIdMembers'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postVaultsVaultIdMembers>>, {vaultId: string;data: ShareVaultRequest}> = (props) => {
          const {vaultId,data} = props ?? {};

          return  postVaultsVaultIdMembers(vaultId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostVaultsVaultIdMembersMutationResult = NonNullable<Awaited<ReturnType<typeof postVaultsVaultIdMembers>>>
    export type PostVaultsVaultIdMembersMutationBody = ShareVaultRequest
    export type PostVaultsVaultIdMembersMutationError = ErrorBody

    /**
 * @summary Share vault
 */
export const usePostVaultsVaultIdMembers = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdMembers>>, TError,{vaultId: string;data: ShareVaultRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postVaultsVaultIdMembers>>,
        TError,
        {vaultId: string;data: ShareVaultRequest},
        TContext
      > => {
      return useMutation(getPostVaultsVaultIdMembersMutationOptions(options), queryClient);
    }
    /**
 * Remove a member from a shared vault and signal rekey requirement
 * @summary Remove member
 */
export type deleteVaultsVaultIdMembersUserIdResponse200 = {
  data: RemoveMemberResponse
  status: 200
}

export type deleteVaultsVaultIdMembersUserIdResponse400 = {
  data: ErrorBody
  status: 400
}

export type deleteVaultsVaultIdMembersUserIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteVaultsVaultIdMembersUserIdResponseSuccess = (deleteVaultsVaultIdMembersUserIdResponse200) & {
  headers: Headers;
};
export type deleteVaultsVaultIdMembersUserIdResponseError = (deleteVaultsVaultIdMembersUserIdResponse400 | deleteVaultsVaultIdMembersUserIdResponse404) & {
  headers: Headers;
};

export type deleteVaultsVaultIdMembersUserIdResponse = (deleteVaultsVaultIdMembersUserIdResponseSuccess | deleteVaultsVaultIdMembersUserIdResponseError)

export const getDeleteVaultsVaultIdMembersUserIdUrl = (vaultId: string,
    userId: string,) => {




  return `/vaults/${vaultId}/members/${userId}`
}

export const deleteVaultsVaultIdMembersUserId = async (vaultId: string,
    userId: string, options?: RequestInit): Promise<deleteVaultsVaultIdMembersUserIdResponse> => {

  return apiFetcher<deleteVaultsVaultIdMembersUserIdResponse>(getDeleteVaultsVaultIdMembersUserIdUrl(vaultId,userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteVaultsVaultIdMembersUserIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdMembersUserId>>, TError,{vaultId: string;userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdMembersUserId>>, TError,{vaultId: string;userId: string}, TContext> => {

const mutationKey = ['deleteVaultsVaultIdMembersUserId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVaultsVaultIdMembersUserId>>, {vaultId: string;userId: string}> = (props) => {
          const {vaultId,userId} = props ?? {};

          return  deleteVaultsVaultIdMembersUserId(vaultId,userId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteVaultsVaultIdMembersUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVaultsVaultIdMembersUserId>>>

    export type DeleteVaultsVaultIdMembersUserIdMutationError = ErrorBody

    /**
 * @summary Remove member
 */
export const useDeleteVaultsVaultIdMembersUserId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdMembersUserId>>, TError,{vaultId: string;userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVaultsVaultIdMembersUserId>>,
        TError,
        {vaultId: string;userId: string},
        TContext
      > => {
      return useMutation(getDeleteVaultsVaultIdMembersUserIdMutationOptions(options), queryClient);
    }
    /**
 * Atomically re-encrypt all items and re-wrap vault keys for remaining members
 * @summary Rekey vault
 */
export type putVaultsVaultIdRekeyResponse204 = {
  data: void
  status: 204
}

export type putVaultsVaultIdRekeyResponse400 = {
  data: ErrorBody
  status: 400
}

export type putVaultsVaultIdRekeyResponse404 = {
  data: ErrorBody
  status: 404
}

export type putVaultsVaultIdRekeyResponseSuccess = (putVaultsVaultIdRekeyResponse204) & {
  headers: Headers;
};
export type putVaultsVaultIdRekeyResponseError = (putVaultsVaultIdRekeyResponse400 | putVaultsVaultIdRekeyResponse404) & {
  headers: Headers;
};

export type putVaultsVaultIdRekeyResponse = (putVaultsVaultIdRekeyResponseSuccess | putVaultsVaultIdRekeyResponseError)

export const getPutVaultsVaultIdRekeyUrl = (vaultId: string,) => {




  return `/vaults/${vaultId}/rekey`
}

export const putVaultsVaultIdRekey = async (vaultId: string,
    rekeyVaultRequest: RekeyVaultRequest, options?: RequestInit): Promise<putVaultsVaultIdRekeyResponse> => {

  return apiFetcher<putVaultsVaultIdRekeyResponse>(getPutVaultsVaultIdRekeyUrl(vaultId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rekeyVaultRequest,)
  }
);}




export const getPutVaultsVaultIdRekeyMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdRekey>>, TError,{vaultId: string;data: RekeyVaultRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdRekey>>, TError,{vaultId: string;data: RekeyVaultRequest}, TContext> => {

const mutationKey = ['putVaultsVaultIdRekey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putVaultsVaultIdRekey>>, {vaultId: string;data: RekeyVaultRequest}> = (props) => {
          const {vaultId,data} = props ?? {};

          return  putVaultsVaultIdRekey(vaultId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutVaultsVaultIdRekeyMutationResult = NonNullable<Awaited<ReturnType<typeof putVaultsVaultIdRekey>>>
    export type PutVaultsVaultIdRekeyMutationBody = RekeyVaultRequest
    export type PutVaultsVaultIdRekeyMutationError = ErrorBody

    /**
 * @summary Rekey vault
 */
export const usePutVaultsVaultIdRekey = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdRekey>>, TError,{vaultId: string;data: RekeyVaultRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putVaultsVaultIdRekey>>,
        TError,
        {vaultId: string;data: RekeyVaultRequest},
        TContext
      > => {
      return useMutation(getPutVaultsVaultIdRekeyMutationOptions(options), queryClient);
    }
