/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  GetVaultsVaultIdItemsParams,
  ItemCreateRequest,
  ItemResponse,
  ItemUpdateRequest
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * List all active (non-trashed) items in a vault with optional filters
 * @summary List items
 */
export type getVaultsVaultIdItemsResponse200 = {
  data: ItemResponse[]
  status: 200
}

export type getVaultsVaultIdItemsResponse404 = {
  data: ErrorBody
  status: 404
}

export type getVaultsVaultIdItemsResponseSuccess = (getVaultsVaultIdItemsResponse200) & {
  headers: Headers;
};
export type getVaultsVaultIdItemsResponseError = (getVaultsVaultIdItemsResponse404) & {
  headers: Headers;
};

export type getVaultsVaultIdItemsResponse = (getVaultsVaultIdItemsResponseSuccess | getVaultsVaultIdItemsResponseError)

export const getGetVaultsVaultIdItemsUrl = (vaultId: string,
    params?: GetVaultsVaultIdItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/vaults/${vaultId}/items?${stringifiedParams}` : `/vaults/${vaultId}/items`
}

export const getVaultsVaultIdItems = async (vaultId: string,
    params?: GetVaultsVaultIdItemsParams, options?: RequestInit): Promise<getVaultsVaultIdItemsResponse> => {

  return apiFetcher<getVaultsVaultIdItemsResponse>(getGetVaultsVaultIdItemsUrl(vaultId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVaultsVaultIdItemsQueryKey = (vaultId: string,
    params?: GetVaultsVaultIdItemsParams,) => {
    return [
    `/vaults/${vaultId}/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetVaultsVaultIdItemsQueryOptions = <TData = Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError = ErrorBody>(vaultId: string,
    params?: GetVaultsVaultIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVaultsVaultIdItemsQueryKey(vaultId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVaultsVaultIdItems>>> = ({ signal }) => getVaultsVaultIdItems(vaultId,params, { signal });





   return  { queryKey, queryFn, enabled: !!(vaultId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVaultsVaultIdItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getVaultsVaultIdItems>>>
export type GetVaultsVaultIdItemsQueryError = ErrorBody


export function useGetVaultsVaultIdItems<TData = Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError = ErrorBody>(
 vaultId: string,
    params: undefined |  GetVaultsVaultIdItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdItems>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdItems<TData = Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError = ErrorBody>(
 vaultId: string,
    params?: GetVaultsVaultIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdItems>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdItems<TData = Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError = ErrorBody>(
 vaultId: string,
    params?: GetVaultsVaultIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List items
 */

export function useGetVaultsVaultIdItems<TData = Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError = ErrorBody>(
 vaultId: string,
    params?: GetVaultsVaultIdItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItems>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVaultsVaultIdItemsQueryOptions(vaultId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new encrypted item in the specified vault
 * @summary Create item
 */
export type postVaultsVaultIdItemsResponse201 = {
  data: ItemResponse
  status: 201
}

export type postVaultsVaultIdItemsResponse400 = {
  data: ErrorBody
  status: 400
}

export type postVaultsVaultIdItemsResponse404 = {
  data: ErrorBody
  status: 404
}

export type postVaultsVaultIdItemsResponseSuccess = (postVaultsVaultIdItemsResponse201) & {
  headers: Headers;
};
export type postVaultsVaultIdItemsResponseError = (postVaultsVaultIdItemsResponse400 | postVaultsVaultIdItemsResponse404) & {
  headers: Headers;
};

export type postVaultsVaultIdItemsResponse = (postVaultsVaultIdItemsResponseSuccess | postVaultsVaultIdItemsResponseError)

export const getPostVaultsVaultIdItemsUrl = (vaultId: string,) => {




  return `/vaults/${vaultId}/items`
}

export const postVaultsVaultIdItems = async (vaultId: string,
    itemCreateRequest: ItemCreateRequest, options?: RequestInit): Promise<postVaultsVaultIdItemsResponse> => {

  return apiFetcher<postVaultsVaultIdItemsResponse>(getPostVaultsVaultIdItemsUrl(vaultId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      itemCreateRequest,)
  }
);}




export const getPostVaultsVaultIdItemsMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdItems>>, TError,{vaultId: string;data: ItemCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdItems>>, TError,{vaultId: string;data: ItemCreateRequest}, TContext> => {

const mutationKey = ['postVaultsVaultIdItems'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postVaultsVaultIdItems>>, {vaultId: string;data: ItemCreateRequest}> = (props) => {
          const {vaultId,data} = props ?? {};

          return  postVaultsVaultIdItems(vaultId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostVaultsVaultIdItemsMutationResult = NonNullable<Awaited<ReturnType<typeof postVaultsVaultIdItems>>>
    export type PostVaultsVaultIdItemsMutationBody = ItemCreateRequest
    export type PostVaultsVaultIdItemsMutationError = ErrorBody

    /**
 * @summary Create item
 */
export const usePostVaultsVaultIdItems = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdItems>>, TError,{vaultId: string;data: ItemCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postVaultsVaultIdItems>>,
        TError,
        {vaultId: string;data: ItemCreateRequest},
        TContext
      > => {
      return useMutation(getPostVaultsVaultIdItemsMutationOptions(options), queryClient);
    }
    /**
 * Retrieve a single encrypted item by ID
 * @summary Get item
 */
export type getVaultsVaultIdItemsIdResponse200 = {
  data: ItemResponse
  status: 200
}

export type getVaultsVaultIdItemsIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type getVaultsVaultIdItemsIdResponseSuccess = (getVaultsVaultIdItemsIdResponse200) & {
  headers: Headers;
};
export type getVaultsVaultIdItemsIdResponseError = (getVaultsVaultIdItemsIdResponse404) & {
  headers: Headers;
};

export type getVaultsVaultIdItemsIdResponse = (getVaultsVaultIdItemsIdResponseSuccess | getVaultsVaultIdItemsIdResponseError)

export const getGetVaultsVaultIdItemsIdUrl = (vaultId: string,
    id: string,) => {




  return `/vaults/${vaultId}/items/${id}`
}

export const getVaultsVaultIdItemsId = async (vaultId: string,
    id: string, options?: RequestInit): Promise<getVaultsVaultIdItemsIdResponse> => {

  return apiFetcher<getVaultsVaultIdItemsIdResponse>(getGetVaultsVaultIdItemsIdUrl(vaultId,id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVaultsVaultIdItemsIdQueryKey = (vaultId: string,
    id: string,) => {
    return [
    `/vaults/${vaultId}/items/${id}`
    ] as const;
    }


export const getGetVaultsVaultIdItemsIdQueryOptions = <TData = Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError = ErrorBody>(vaultId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVaultsVaultIdItemsIdQueryKey(vaultId,id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>> = ({ signal }) => getVaultsVaultIdItemsId(vaultId,id, { signal });





   return  { queryKey, queryFn, enabled: !!(vaultId && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVaultsVaultIdItemsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>>
export type GetVaultsVaultIdItemsIdQueryError = ErrorBody


export function useGetVaultsVaultIdItemsId<TData = Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError = ErrorBody>(
 vaultId: string,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdItemsId<TData = Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError = ErrorBody>(
 vaultId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdItemsId<TData = Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError = ErrorBody>(
 vaultId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get item
 */

export function useGetVaultsVaultIdItemsId<TData = Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError = ErrorBody>(
 vaultId: string,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdItemsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVaultsVaultIdItemsIdQueryOptions(vaultId,id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update an existing encrypted item
 * @summary Update item
 */
export type putVaultsVaultIdItemsIdResponse200 = {
  data: ItemResponse
  status: 200
}

export type putVaultsVaultIdItemsIdResponse400 = {
  data: ErrorBody
  status: 400
}

export type putVaultsVaultIdItemsIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type putVaultsVaultIdItemsIdResponseSuccess = (putVaultsVaultIdItemsIdResponse200) & {
  headers: Headers;
};
export type putVaultsVaultIdItemsIdResponseError = (putVaultsVaultIdItemsIdResponse400 | putVaultsVaultIdItemsIdResponse404) & {
  headers: Headers;
};

export type putVaultsVaultIdItemsIdResponse = (putVaultsVaultIdItemsIdResponseSuccess | putVaultsVaultIdItemsIdResponseError)

export const getPutVaultsVaultIdItemsIdUrl = (vaultId: string,
    id: string,) => {




  return `/vaults/${vaultId}/items/${id}`
}

export const putVaultsVaultIdItemsId = async (vaultId: string,
    id: string,
    itemUpdateRequest: ItemUpdateRequest, options?: RequestInit): Promise<putVaultsVaultIdItemsIdResponse> => {

  return apiFetcher<putVaultsVaultIdItemsIdResponse>(getPutVaultsVaultIdItemsIdUrl(vaultId,id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      itemUpdateRequest,)
  }
);}




export const getPutVaultsVaultIdItemsIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdItemsId>>, TError,{vaultId: string;id: string;data: ItemUpdateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdItemsId>>, TError,{vaultId: string;id: string;data: ItemUpdateRequest}, TContext> => {

const mutationKey = ['putVaultsVaultIdItemsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putVaultsVaultIdItemsId>>, {vaultId: string;id: string;data: ItemUpdateRequest}> = (props) => {
          const {vaultId,id,data} = props ?? {};

          return  putVaultsVaultIdItemsId(vaultId,id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutVaultsVaultIdItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putVaultsVaultIdItemsId>>>
    export type PutVaultsVaultIdItemsIdMutationBody = ItemUpdateRequest
    export type PutVaultsVaultIdItemsIdMutationError = ErrorBody

    /**
 * @summary Update item
 */
export const usePutVaultsVaultIdItemsId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putVaultsVaultIdItemsId>>, TError,{vaultId: string;id: string;data: ItemUpdateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putVaultsVaultIdItemsId>>,
        TError,
        {vaultId: string;id: string;data: ItemUpdateRequest},
        TContext
      > => {
      return useMutation(getPutVaultsVaultIdItemsIdMutationOptions(options), queryClient);
    }
    /**
 * Move an item to trash (soft delete)
 * @summary Trash item
 */
export type deleteVaultsVaultIdItemsIdResponse204 = {
  data: void
  status: 204
}

export type deleteVaultsVaultIdItemsIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteVaultsVaultIdItemsIdResponseSuccess = (deleteVaultsVaultIdItemsIdResponse204) & {
  headers: Headers;
};
export type deleteVaultsVaultIdItemsIdResponseError = (deleteVaultsVaultIdItemsIdResponse404) & {
  headers: Headers;
};

export type deleteVaultsVaultIdItemsIdResponse = (deleteVaultsVaultIdItemsIdResponseSuccess | deleteVaultsVaultIdItemsIdResponseError)

export const getDeleteVaultsVaultIdItemsIdUrl = (vaultId: string,
    id: string,) => {




  return `/vaults/${vaultId}/items/${id}`
}

export const deleteVaultsVaultIdItemsId = async (vaultId: string,
    id: string, options?: RequestInit): Promise<deleteVaultsVaultIdItemsIdResponse> => {

  return apiFetcher<deleteVaultsVaultIdItemsIdResponse>(getDeleteVaultsVaultIdItemsIdUrl(vaultId,id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteVaultsVaultIdItemsIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdItemsId>>, TError,{vaultId: string;id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdItemsId>>, TError,{vaultId: string;id: string}, TContext> => {

const mutationKey = ['deleteVaultsVaultIdItemsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVaultsVaultIdItemsId>>, {vaultId: string;id: string}> = (props) => {
          const {vaultId,id} = props ?? {};

          return  deleteVaultsVaultIdItemsId(vaultId,id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteVaultsVaultIdItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVaultsVaultIdItemsId>>>

    export type DeleteVaultsVaultIdItemsIdMutationError = ErrorBody

    /**
 * @summary Trash item
 */
export const useDeleteVaultsVaultIdItemsId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdItemsId>>, TError,{vaultId: string;id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVaultsVaultIdItemsId>>,
        TError,
        {vaultId: string;id: string},
        TContext
      > => {
      return useMutation(getDeleteVaultsVaultIdItemsIdMutationOptions(options), queryClient);
    }
