/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  VaultCreateRequest,
  VaultResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Returns all vaults the authenticated user has access to
 * @summary List vaults
 */
export type getVaultsResponse200 = {
  data: VaultResponse[]
  status: 200
}

export type getVaultsResponse401 = {
  data: ErrorBody
  status: 401
}

export type getVaultsResponseSuccess = (getVaultsResponse200) & {
  headers: Headers;
};
export type getVaultsResponseError = (getVaultsResponse401) & {
  headers: Headers;
};

export type getVaultsResponse = (getVaultsResponseSuccess | getVaultsResponseError)

export const getGetVaultsUrl = () => {




  return `/vaults`
}

export const getVaults = async ( options?: RequestInit): Promise<getVaultsResponse> => {

  return apiFetcher<getVaultsResponse>(getGetVaultsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVaultsQueryKey = () => {
    return [
    `/vaults`
    ] as const;
    }


export const getGetVaultsQueryOptions = <TData = Awaited<ReturnType<typeof getVaults>>, TError = ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVaultsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVaults>>> = ({ signal }) => getVaults({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVaultsQueryResult = NonNullable<Awaited<ReturnType<typeof getVaults>>>
export type GetVaultsQueryError = ErrorBody


export function useGetVaults<TData = Awaited<ReturnType<typeof getVaults>>, TError = ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaults>>,
          TError,
          Awaited<ReturnType<typeof getVaults>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaults<TData = Awaited<ReturnType<typeof getVaults>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaults>>,
          TError,
          Awaited<ReturnType<typeof getVaults>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaults<TData = Awaited<ReturnType<typeof getVaults>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List vaults
 */

export function useGetVaults<TData = Awaited<ReturnType<typeof getVaults>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaults>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVaultsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new vault with an encrypted vault key
 * @summary Create vault
 */
export type postVaultsResponse201 = {
  data: VaultResponse
  status: 201
}

export type postVaultsResponse400 = {
  data: ErrorBody
  status: 400
}

export type postVaultsResponse401 = {
  data: ErrorBody
  status: 401
}

export type postVaultsResponseSuccess = (postVaultsResponse201) & {
  headers: Headers;
};
export type postVaultsResponseError = (postVaultsResponse400 | postVaultsResponse401) & {
  headers: Headers;
};

export type postVaultsResponse = (postVaultsResponseSuccess | postVaultsResponseError)

export const getPostVaultsUrl = () => {




  return `/vaults`
}

export const postVaults = async (vaultCreateRequest: VaultCreateRequest, options?: RequestInit): Promise<postVaultsResponse> => {

  return apiFetcher<postVaultsResponse>(getPostVaultsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      vaultCreateRequest,)
  }
);}




export const getPostVaultsMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaults>>, TError,{data: VaultCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postVaults>>, TError,{data: VaultCreateRequest}, TContext> => {

const mutationKey = ['postVaults'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postVaults>>, {data: VaultCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postVaults(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostVaultsMutationResult = NonNullable<Awaited<ReturnType<typeof postVaults>>>
    export type PostVaultsMutationBody = VaultCreateRequest
    export type PostVaultsMutationError = ErrorBody

    /**
 * @summary Create vault
 */
export const usePostVaults = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaults>>, TError,{data: VaultCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postVaults>>,
        TError,
        {data: VaultCreateRequest},
        TContext
      > => {
      return useMutation(getPostVaultsMutationOptions(options), queryClient);
    }
