#!/usr/bin/env bash
#
# vaultctl interactive installer
# Usage: curl -fsSL https://vaultctl.dev/install.sh | bash
#
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

print_banner() {
  echo -e "${BLUE}"
  echo "  ╔══════════════════════════════════════╗"
  echo "  ║                                      ║"
  echo "  ║     vaultctl installer               ║"
  echo "  ║     Zero-knowledge password vault    ║"
  echo "  ║                                      ║"
  echo "  ╚══════════════════════════════════════╝"
  echo -e "${NC}"
}

info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

prompt() {
  local msg="$1" default="${2:-}"
  if [ -n "$default" ]; then
    read -rp "$(echo -e "${BOLD}$msg${NC} [$default]: ")" answer
    echo "${answer:-$default}"
  else
    read -rp "$(echo -e "${BOLD}$msg${NC}: ")" answer
    echo "$answer"
  fi
}

confirm() {
  local msg="$1"
  read -rp "$(echo -e "${BOLD}$msg${NC} [y/N]: ")" answer
  [[ "$answer" =~ ^[Yy]$ ]]
}

generate_secret() { openssl rand -base64 "$1" | tr -d '\n'; }
generate_secret_urlsafe() { openssl rand -hex "$1"; }

# =========================================================================
print_banner

# Step 1: Check prerequisites
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
  warn "Docker not found."
  if confirm "Install Docker?"; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo systemctl enable --now docker
    sudo usermod -aG docker "$USER"
    success "Docker installed. You may need to log out and back in for group changes."
  else
    error "Docker is required. Install it manually: https://docs.docker.com/get-docker/"
  fi
fi
success "Docker $(docker --version | awk '{print $3}' | tr -d ',')"

if ! docker compose version &>/dev/null; then
  error "Docker Compose plugin not found. Install: https://docs.docker.com/compose/install/"
fi
success "Docker Compose $(docker compose version --short)"

if ! command -v openssl &>/dev/null; then
  error "openssl is required for secret generation"
fi

# Step 2: Choose install directory
echo ""
INSTALL_DIR=$(prompt "Installation directory" "$HOME/vaultctl")
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"
info "Installing to $INSTALL_DIR"

# Step 3: Download or update source
if [ -d ".git" ]; then
  info "Existing repository found, pulling latest..."
  git pull --ff-only
else
  info "Downloading vaultctl..."
  if command -v git &>/dev/null; then
    git clone --depth 1 https://github.com/vineethkrishnan/vaultctl.git .
  else
    curl -fsSL https://github.com/vineethkrishnan/vaultctl/archive/refs/heads/main.tar.gz | tar xz --strip-components=1
  fi
fi
success "Source downloaded"

# Step 4: Configure domain
echo ""
DOMAIN=$(prompt "Your domain (e.g., vault.example.com)" "localhost")

# Step 5: Choose deployment mode
echo ""
info "Deployment modes:"
echo -e "  ${BOLD}1)${NC} Full stack — Caddy (auto-TLS) + vaultctl + Postgres"
echo -e "  ${BOLD}2)${NC} Simple    — vaultctl + Postgres (BYO reverse proxy)"
echo ""
MODE=$(prompt "Choose mode" "1")

# Step 6: Generate cryptographic secrets
echo ""
info "Generating cryptographic secrets..."

JWT_SECRET=$(generate_secret 64)
SERVER_PEPPER=$(generate_secret 32)
ENUM_PEPPER=$(generate_secret 32)
DATA_KEY=$(generate_secret 32)
DB_PASSWORD=$(openssl rand -hex 16)

success "Secrets generated (JWT 64-byte, peppers + DEK 32-byte each)"

# Step 7: Determine base URL
if [ "$DOMAIN" = "localhost" ]; then
  BASE_URL="http://localhost:8080"
else
  BASE_URL="https://${DOMAIN}"
fi

# Step 8: Write .env (matches config.go field names exactly)
if [ -f .env ]; then
  warn ".env already exists"
  if ! confirm "Overwrite?"; then
    info "Keeping existing .env"
  else
    WRITE_ENV=1
  fi
else
  WRITE_ENV=1
fi

if [ "${WRITE_ENV:-0}" = "1" ]; then
  cat > .env << EOF
# vaultctl configuration — generated by installer on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# See .env.example for full reference.

# ===========================================================================
# Server
# ===========================================================================
VAULTCTL_ENV=production
VAULTCTL_PORT=8080
VAULTCTL_HOST=0.0.0.0
VAULTCTL_BASE_URL=${BASE_URL}

# ===========================================================================
# Database (individual fields — NOT a connection URL)
# ===========================================================================
VAULTCTL_DB_HOST=vaultctl-db
VAULTCTL_DB_PORT=5432
VAULTCTL_DB_NAME=vaultctl
VAULTCTL_DB_USER=vaultctl
VAULTCTL_DB_PASSWORD=${DB_PASSWORD}
# H12: SSL mode is overridden to 'disable' inside docker-compose.yml
# for the loopback container network. Do NOT change this to 'disable' here.
VAULTCTL_DB_SSL_MODE=require

# ===========================================================================
# JWT signing keys — dual-key rotation (H8)
# ===========================================================================
VAULTCTL_JWT_SECRET_CURRENT=${JWT_SECRET}
VAULTCTL_JWT_SECRET_NEXT=
VAULTCTL_JWT_KID_CURRENT=k1
VAULTCTL_JWT_ACCESS_TTL=15m
VAULTCTL_JWT_REFRESH_TTL=168h

# ===========================================================================
# Server-side data encryption key (H5)
# ===========================================================================
VAULTCTL_DATA_ENCRYPTION_KEY=${DATA_KEY}
VAULTCTL_DATA_ENCRYPTION_KEY_NEXT=

# ===========================================================================
# Server peppers (C3 / H7 / H2) — never rotate casually
# ===========================================================================
VAULTCTL_SERVER_PEPPER=${SERVER_PEPPER}
VAULTCTL_ENUMERATION_PEPPER=${ENUM_PEPPER}

# ===========================================================================
# Security
# ===========================================================================
VAULTCTL_REGISTRATION_MODE=open
VAULTCTL_MAX_LOGIN_ATTEMPTS=5
VAULTCTL_LOCKOUT_DURATION=15m
VAULTCTL_RATE_LIMIT_RPM=60
VAULTCTL_AUTH_RATE_LIMIT_PER_EMAIL=5
VAULTCTL_AUTH_RATE_LIMIT_WINDOW=15m
VAULTCTL_STEP_UP_MAX_AGE=5m
VAULTCTL_TRUSTED_PROXIES=127.0.0.1/32,172.16.0.0/12
VAULTCTL_CORS_ALLOWED_ORIGINS=${BASE_URL}

# ===========================================================================
# Retention
# ===========================================================================
VAULTCTL_TRASH_RETENTION_DAYS=30
VAULTCTL_BACKUP_RETENTION_DAYS=90

# ===========================================================================
# Logging
# ===========================================================================
VAULTCTL_LOG_LEVEL=info
VAULTCTL_LOG_FORMAT=json
EOF
  success ".env configured"
fi

# Step 9: Configure Caddy for domain (full-stack mode only)
if [ "$MODE" = "1" ] && [ "$DOMAIN" != "localhost" ]; then
  # The deploy/caddy/Caddyfile from the repo is used by docker-compose.yml.
  # It reads VAULTCTL_BASE_URL from the environment, so no rewrite needed.
  success "Caddy will use auto-TLS for ${DOMAIN}"
elif [ "$MODE" = "1" ] && [ "$DOMAIN" = "localhost" ]; then
  warn "Using localhost with Caddy — no TLS. For production, re-run with a real domain."
fi

# Step 10: Select compose file
if [ "$MODE" = "1" ]; then
  COMPOSE_FILE="docker-compose.yml"
else
  COMPOSE_FILE="docker-compose.simple.yml"
fi

# Step 11: Start services
echo ""
if confirm "Start vaultctl now?"; then
  info "Starting services with ${COMPOSE_FILE}..."
  docker compose -f "$COMPOSE_FILE" pull
  docker compose -f "$COMPOSE_FILE" up -d

  # Wait for health
  info "Waiting for server to be ready..."
  HEALTH_URL="http://localhost:8080/api/v1/health"
  READY=0
  for i in $(seq 1 30); do
    if curl -sf "$HEALTH_URL" &>/dev/null; then
      READY=1
      break
    fi
    sleep 2
  done

  if [ "$READY" = "1" ]; then
    success "vaultctl is running!"
  else
    warn "Server not yet responding. Check logs: docker compose -f ${COMPOSE_FILE} logs -f"
  fi
else
  info "To start later: cd ${INSTALL_DIR} && docker compose -f ${COMPOSE_FILE} up -d --build"
fi

# Step 12: Summary
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ${BOLD}vaultctl installed successfully!${NC}${GREEN}             ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Web vault:${NC}    ${BASE_URL}"
echo -e "  ${BOLD}Health:${NC}       curl http://localhost:8080/api/v1/health"
echo -e "  ${BOLD}Logs:${NC}         cd ${INSTALL_DIR} && docker compose -f ${COMPOSE_FILE} logs -f"
echo -e "  ${BOLD}Stop:${NC}         cd ${INSTALL_DIR} && docker compose -f ${COMPOSE_FILE} down"
echo -e "  ${BOLD}Backup:${NC}       docker exec vaultctl-api /usr/local/bin/vaultctl backup"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "    1. Open ${BASE_URL} in your browser"
echo -e "    2. Create your account (registration mode is 'open')"
echo -e "    3. Save your recovery kit"
echo -e "    4. Change VAULTCTL_REGISTRATION_MODE to 'invite' in .env"
echo -e "       then restart: docker compose -f ${COMPOSE_FILE} restart vaultctl"
echo ""
echo -e "  ${YELLOW}Security note:${NC}"
echo -e "    Your secrets are in ${INSTALL_DIR}/.env"
echo -e "    Back up this file securely — if lost, all encrypted data is unrecoverable."
echo ""
echo -e "  ${BOLD}Documentation:${NC} https://docs.vaultctl.dev"
echo ""
