/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  APIKeyResponse,
  CreateAPIKeyRequest,
  CreateAPIKeyResponse,
  ErrorBody
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Returns all API keys for the authenticated user (without raw key values)
 * @summary List API keys
 */
export type getApiKeysResponse200 = {
  data: APIKeyResponse[]
  status: 200
}

export type getApiKeysResponse401 = {
  data: ErrorBody
  status: 401
}

export type getApiKeysResponseSuccess = (getApiKeysResponse200) & {
  headers: Headers;
};
export type getApiKeysResponseError = (getApiKeysResponse401) & {
  headers: Headers;
};

export type getApiKeysResponse = (getApiKeysResponseSuccess | getApiKeysResponseError)

export const getGetApiKeysUrl = () => {




  return `/api-keys`
}

export const getApiKeys = async ( options?: RequestInit): Promise<getApiKeysResponse> => {

  return apiFetcher<getApiKeysResponse>(getGetApiKeysUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiKeysQueryKey = () => {
    return [
    `/api-keys`
    ] as const;
    }


export const getGetApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof getApiKeys>>, TError = ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiKeysQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiKeys>>> = ({ signal }) => getApiKeys({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof getApiKeys>>>
export type GetApiKeysQueryError = ErrorBody


export function useGetApiKeys<TData = Awaited<ReturnType<typeof getApiKeys>>, TError = ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getApiKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiKeys<TData = Awaited<ReturnType<typeof getApiKeys>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getApiKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiKeys<TData = Awaited<ReturnType<typeof getApiKeys>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List API keys
 */

export function useGetApiKeys<TData = Awaited<ReturnType<typeof getApiKeys>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiKeys>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiKeysQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Generate a new personal API key for programmatic access. The raw key is returned only once.
 * @summary Create API key
 */
export type postApiKeysResponse201 = {
  data: CreateAPIKeyResponse
  status: 201
}

export type postApiKeysResponse400 = {
  data: ErrorBody
  status: 400
}

export type postApiKeysResponse401 = {
  data: ErrorBody
  status: 401
}

export type postApiKeysResponseSuccess = (postApiKeysResponse201) & {
  headers: Headers;
};
export type postApiKeysResponseError = (postApiKeysResponse400 | postApiKeysResponse401) & {
  headers: Headers;
};

export type postApiKeysResponse = (postApiKeysResponseSuccess | postApiKeysResponseError)

export const getPostApiKeysUrl = () => {




  return `/api-keys`
}

export const postApiKeys = async (createAPIKeyRequest: CreateAPIKeyRequest, options?: RequestInit): Promise<postApiKeysResponse> => {

  return apiFetcher<postApiKeysResponse>(getPostApiKeysUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAPIKeyRequest,)
  }
);}




export const getPostApiKeysMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext> => {

const mutationKey = ['postApiKeys'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiKeys>>, {data: CreateAPIKeyRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiKeys(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiKeysMutationResult = NonNullable<Awaited<ReturnType<typeof postApiKeys>>>
    export type PostApiKeysMutationBody = CreateAPIKeyRequest
    export type PostApiKeysMutationError = ErrorBody

    /**
 * @summary Create API key
 */
export const usePostApiKeys = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiKeys>>,
        TError,
        {data: CreateAPIKeyRequest},
        TContext
      > => {
      return useMutation(getPostApiKeysMutationOptions(options), queryClient);
    }
    /**
 * Permanently delete a personal API key
 * @summary Delete API key
 */
export type deleteApiKeysIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiKeysIdResponse401 = {
  data: ErrorBody
  status: 401
}

export type deleteApiKeysIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteApiKeysIdResponseSuccess = (deleteApiKeysIdResponse204) & {
  headers: Headers;
};
export type deleteApiKeysIdResponseError = (deleteApiKeysIdResponse401 | deleteApiKeysIdResponse404) & {
  headers: Headers;
};

export type deleteApiKeysIdResponse = (deleteApiKeysIdResponseSuccess | deleteApiKeysIdResponseError)

export const getDeleteApiKeysIdUrl = (id: string,) => {




  return `/api-keys/${id}`
}

export const deleteApiKeysId = async (id: string, options?: RequestInit): Promise<deleteApiKeysIdResponse> => {

  return apiFetcher<deleteApiKeysIdResponse>(getDeleteApiKeysIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiKeysIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiKeysId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiKeysId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiKeysId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiKeysId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiKeysId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiKeysIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiKeysId>>>

    export type DeleteApiKeysIdMutationError = ErrorBody

    /**
 * @summary Delete API key
 */
export const useDeleteApiKeysId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiKeysId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiKeysId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiKeysIdMutationOptions(options), queryClient);
    }
