/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  APIKeyResponse,
  CreateAPIKeyRequest,
  CreateAPIKeyResponse,
  ErrorBody
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Returns all API keys for the authenticated user (without raw key values)
 * @summary List API keys
 */
export type getUsersMeApiKeysResponse200 = {
  data: APIKeyResponse[]
  status: 200
}

export type getUsersMeApiKeysResponse401 = {
  data: ErrorBody
  status: 401
}

export type getUsersMeApiKeysResponseSuccess = (getUsersMeApiKeysResponse200) & {
  headers: Headers;
};
export type getUsersMeApiKeysResponseError = (getUsersMeApiKeysResponse401) & {
  headers: Headers;
};

export type getUsersMeApiKeysResponse = (getUsersMeApiKeysResponseSuccess | getUsersMeApiKeysResponseError)

export const getGetUsersMeApiKeysUrl = () => {




  return `/users/me/api-keys`
}

export const getUsersMeApiKeys = async ( options?: RequestInit): Promise<getUsersMeApiKeysResponse> => {

  return apiFetcher<getUsersMeApiKeysResponse>(getGetUsersMeApiKeysUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersMeApiKeysQueryKey = () => {
    return [
    `/users/me/api-keys`
    ] as const;
    }


export const getGetUsersMeApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError = ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersMeApiKeysQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersMeApiKeys>>> = ({ signal }) => getUsersMeApiKeys({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersMeApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersMeApiKeys>>>
export type GetUsersMeApiKeysQueryError = ErrorBody


export function useGetUsersMeApiKeys<TData = Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError = ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMeApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getUsersMeApiKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMeApiKeys<TData = Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMeApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getUsersMeApiKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMeApiKeys<TData = Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List API keys
 */

export function useGetUsersMeApiKeys<TData = Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeApiKeys>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersMeApiKeysQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Generate a new personal API key for programmatic access. The raw key is returned only once.
 * @summary Create API key
 */
export type postUsersMeApiKeysResponse201 = {
  data: CreateAPIKeyResponse
  status: 201
}

export type postUsersMeApiKeysResponse400 = {
  data: ErrorBody
  status: 400
}

export type postUsersMeApiKeysResponse401 = {
  data: ErrorBody
  status: 401
}

export type postUsersMeApiKeysResponseSuccess = (postUsersMeApiKeysResponse201) & {
  headers: Headers;
};
export type postUsersMeApiKeysResponseError = (postUsersMeApiKeysResponse400 | postUsersMeApiKeysResponse401) & {
  headers: Headers;
};

export type postUsersMeApiKeysResponse = (postUsersMeApiKeysResponseSuccess | postUsersMeApiKeysResponseError)

export const getPostUsersMeApiKeysUrl = () => {




  return `/users/me/api-keys`
}

export const postUsersMeApiKeys = async (createAPIKeyRequest: CreateAPIKeyRequest, options?: RequestInit): Promise<postUsersMeApiKeysResponse> => {

  return apiFetcher<postUsersMeApiKeysResponse>(getPostUsersMeApiKeysUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAPIKeyRequest,)
  }
);}




export const getPostUsersMeApiKeysMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersMeApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postUsersMeApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext> => {

const mutationKey = ['postUsersMeApiKeys'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsersMeApiKeys>>, {data: CreateAPIKeyRequest}> = (props) => {
          const {data} = props ?? {};

          return  postUsersMeApiKeys(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersMeApiKeysMutationResult = NonNullable<Awaited<ReturnType<typeof postUsersMeApiKeys>>>
    export type PostUsersMeApiKeysMutationBody = CreateAPIKeyRequest
    export type PostUsersMeApiKeysMutationError = ErrorBody

    /**
 * @summary Create API key
 */
export const usePostUsersMeApiKeys = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersMeApiKeys>>, TError,{data: CreateAPIKeyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsersMeApiKeys>>,
        TError,
        {data: CreateAPIKeyRequest},
        TContext
      > => {
      return useMutation(getPostUsersMeApiKeysMutationOptions(options), queryClient);
    }
    /**
 * Permanently delete a personal API key
 * @summary Delete API key
 */
export type deleteUsersMeApiKeysIdResponse204 = {
  data: void
  status: 204
}

export type deleteUsersMeApiKeysIdResponse401 = {
  data: ErrorBody
  status: 401
}

export type deleteUsersMeApiKeysIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteUsersMeApiKeysIdResponseSuccess = (deleteUsersMeApiKeysIdResponse204) & {
  headers: Headers;
};
export type deleteUsersMeApiKeysIdResponseError = (deleteUsersMeApiKeysIdResponse401 | deleteUsersMeApiKeysIdResponse404) & {
  headers: Headers;
};

export type deleteUsersMeApiKeysIdResponse = (deleteUsersMeApiKeysIdResponseSuccess | deleteUsersMeApiKeysIdResponseError)

export const getDeleteUsersMeApiKeysIdUrl = (id: string,) => {




  return `/users/me/api-keys/${id}`
}

export const deleteUsersMeApiKeysId = async (id: string, options?: RequestInit): Promise<deleteUsersMeApiKeysIdResponse> => {

  return apiFetcher<deleteUsersMeApiKeysIdResponse>(getDeleteUsersMeApiKeysIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteUsersMeApiKeysIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersMeApiKeysId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsersMeApiKeysId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteUsersMeApiKeysId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsersMeApiKeysId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteUsersMeApiKeysId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsersMeApiKeysIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsersMeApiKeysId>>>

    export type DeleteUsersMeApiKeysIdMutationError = ErrorBody

    /**
 * @summary Delete API key
 */
export const useDeleteUsersMeApiKeysId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersMeApiKeysId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsersMeApiKeysId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteUsersMeApiKeysIdMutationOptions(options), queryClient);
    }
