// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/content-scripts/webauthn-relay.js"
    | "/emblem.svg"
    | "/fonts/vaultctl-brand.woff2"
    | "/icon/icon-128.png"
    | "/icon/icon-16.png"
    | "/icon/icon-32.png"
    | "/icon/icon-48.png"
    | "/logo.svg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
