/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface CreateAPIKeyResponse {
  expiresAt?: string;
  id?: string;
  /** raw key, shown only once */
  key?: string;
  keyPrefix?: string;
  name?: string;
}
