/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface CreateInviteRequest {
  email?: string;
  /** duration string, e.g. "24h" */
  expiresIn?: string;
  role?: string;
}
