/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export type GetVaultsVaultIdItemsParams = {
/**
 * Filter favorites only
 */
favorites?: boolean;
/**
 * Filter by folder ID
 */
folderId?: string;
/**
 * Filter by item type (login, note, card, identity, api_key, ssh_key, passkey)
 */
itemType?: string;
};
