/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import type { GithubComVineethkrishnanVaultctlInternalApplicationAuthExportFolder } from './githubComVineethkrishnanVaultctlInternalApplicationAuthExportFolder';
import type { GithubComVineethkrishnanVaultctlInternalApplicationAuthExportItem } from './githubComVineethkrishnanVaultctlInternalApplicationAuthExportItem';
import type { GithubComVineethkrishnanVaultctlInternalApplicationAuthExportVault } from './githubComVineethkrishnanVaultctlInternalApplicationAuthExportVault';

export interface GithubComVineethkrishnanVaultctlInternalApplicationAuthExportData {
  folders?: GithubComVineethkrishnanVaultctlInternalApplicationAuthExportFolder[];
  items?: GithubComVineethkrishnanVaultctlInternalApplicationAuthExportItem[];
  vaults?: GithubComVineethkrishnanVaultctlInternalApplicationAuthExportVault[];
}
