/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface ImportItemDTO {
  /** base64 wire-format blob */
  encryptedData?: string;
  /** base64 wire-format blob */
  encryptedName?: string;
  folderId?: string;
  itemType?: string;
}
