/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface LoginRequest {
  /** redacted via LOG_REDACT_FIELDS (C4) */
  authHash?: string;
  deviceName?: string;
  email?: string;
}
