/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import type { VaultMembershipDTO } from './vaultMembershipDTO';

export interface LoginResponse {
  accessToken?: string;
  encryptedIdentityPrivateKey?: string;
  /** User crypto material for client-side key hydration (§4.2) */
  encryptedPrivateKey?: string;
  identityPublicKey?: string;
  publicKey?: string;
  publicKeySignature?: string;
  refreshExpiresAt?: string;
  refreshToken?: string;
  role?: string;
  sessionId?: string;
  upgradeAuthHash?: boolean;
  userId?: string;
  /** Vault memberships with wrapped keys */
  vaults?: VaultMembershipDTO[];
}
