/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface RegisterRequest {
  /** base64 */
  authHash?: string;
  email?: string;
  encryptedIdentityPrivateKey?: string;
  encryptedPrivateKey?: string;
  identityPublicKey?: string;
  kdfIterations?: number;
  kdfMemoryKB?: number;
  kdfParallelism?: number;
  masterPasswordPreflight?: string;
  name?: string;
  publicKey?: string;
  publicKeySignature?: string;
  /** base64 */
  salt?: string;
}
