/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import type { VaultMembershipDTO } from './vaultMembershipDTO';

export interface RemoveMemberResponse {
  rekeyRequired?: boolean;
  remainingMembers?: VaultMembershipDTO[];
}
