/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface UserProfileResponse {
  createdAt?: string;
  email?: string;
  id?: string;
  name?: string;
  role?: string;
}
