/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface VaultMembershipDTO {
  encryptedVaultKey?: string;
  role?: string;
  senderId?: string;
  vaultId?: string;
  vaultName?: string;
  vaultType?: string;
  wrapSignature?: string;
}
