/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */

export interface VaultResponse {
  createdAt?: string;
  encryptedVaultKey?: string;
  id?: string;
  name?: string;
  role?: string;
  senderId?: string;
  type?: string;
  wrapSignature?: string;
}
