/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  SessionResponse,
  UpdateProfileRequest,
  UserProfileResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Returns the profile of the authenticated user
 * @summary Get user profile
 */
export type getUsersMeResponse200 = {
  data: UserProfileResponse
  status: 200
}

export type getUsersMeResponse401 = {
  data: ErrorBody
  status: 401
}

export type getUsersMeResponse404 = {
  data: ErrorBody
  status: 404
}

export type getUsersMeResponseSuccess = (getUsersMeResponse200) & {
  headers: Headers;
};
export type getUsersMeResponseError = (getUsersMeResponse401 | getUsersMeResponse404) & {
  headers: Headers;
};

export type getUsersMeResponse = (getUsersMeResponseSuccess | getUsersMeResponseError)

export const getGetUsersMeUrl = () => {




  return `/users/me`
}

export const getUsersMe = async ( options?: RequestInit): Promise<getUsersMeResponse> => {

  return apiFetcher<getUsersMeResponse>(getGetUsersMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersMeQueryKey = () => {
    return [
    `/users/me`
    ] as const;
    }


export const getGetUsersMeQueryOptions = <TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersMe>>> = ({ signal }) => getUsersMe({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersMe>>>
export type GetUsersMeQueryError = ErrorBody


export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMe>>,
          TError,
          Awaited<ReturnType<typeof getUsersMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMe>>,
          TError,
          Awaited<ReturnType<typeof getUsersMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user profile
 */

export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update the authenticated user's display name
 * @summary Update user profile
 */
export type putUsersMeResponse200 = {
  data: UserProfileResponse
  status: 200
}

export type putUsersMeResponse400 = {
  data: ErrorBody
  status: 400
}

export type putUsersMeResponse401 = {
  data: ErrorBody
  status: 401
}

export type putUsersMeResponse404 = {
  data: ErrorBody
  status: 404
}

export type putUsersMeResponseSuccess = (putUsersMeResponse200) & {
  headers: Headers;
};
export type putUsersMeResponseError = (putUsersMeResponse400 | putUsersMeResponse401 | putUsersMeResponse404) & {
  headers: Headers;
};

export type putUsersMeResponse = (putUsersMeResponseSuccess | putUsersMeResponseError)

export const getPutUsersMeUrl = () => {




  return `/users/me`
}

export const putUsersMe = async (updateProfileRequest: UpdateProfileRequest, options?: RequestInit): Promise<putUsersMeResponse> => {

  return apiFetcher<putUsersMeResponse>(getPutUsersMeUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileRequest,)
  }
);}




export const getPutUsersMeMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersMe>>, TError,{data: UpdateProfileRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putUsersMe>>, TError,{data: UpdateProfileRequest}, TContext> => {

const mutationKey = ['putUsersMe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUsersMe>>, {data: UpdateProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  putUsersMe(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutUsersMeMutationResult = NonNullable<Awaited<ReturnType<typeof putUsersMe>>>
    export type PutUsersMeMutationBody = UpdateProfileRequest
    export type PutUsersMeMutationError = ErrorBody

    /**
 * @summary Update user profile
 */
export const usePutUsersMe = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersMe>>, TError,{data: UpdateProfileRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUsersMe>>,
        TError,
        {data: UpdateProfileRequest},
        TContext
      > => {
      return useMutation(getPutUsersMeMutationOptions(options), queryClient);
    }
    /**
 * Returns all active sessions for the authenticated user
 * @summary List sessions
 */
export type getUsersMeSessionsResponse200 = {
  data: SessionResponse[]
  status: 200
}

export type getUsersMeSessionsResponse401 = {
  data: ErrorBody
  status: 401
}

export type getUsersMeSessionsResponseSuccess = (getUsersMeSessionsResponse200) & {
  headers: Headers;
};
export type getUsersMeSessionsResponseError = (getUsersMeSessionsResponse401) & {
  headers: Headers;
};

export type getUsersMeSessionsResponse = (getUsersMeSessionsResponseSuccess | getUsersMeSessionsResponseError)

export const getGetUsersMeSessionsUrl = () => {




  return `/users/me/sessions`
}

export const getUsersMeSessions = async ( options?: RequestInit): Promise<getUsersMeSessionsResponse> => {

  return apiFetcher<getUsersMeSessionsResponse>(getGetUsersMeSessionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersMeSessionsQueryKey = () => {
    return [
    `/users/me/sessions`
    ] as const;
    }


export const getGetUsersMeSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getUsersMeSessions>>, TError = ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeSessions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersMeSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersMeSessions>>> = ({ signal }) => getUsersMeSessions({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersMeSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersMeSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersMeSessions>>>
export type GetUsersMeSessionsQueryError = ErrorBody


export function useGetUsersMeSessions<TData = Awaited<ReturnType<typeof getUsersMeSessions>>, TError = ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMeSessions>>,
          TError,
          Awaited<ReturnType<typeof getUsersMeSessions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMeSessions<TData = Awaited<ReturnType<typeof getUsersMeSessions>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMeSessions>>,
          TError,
          Awaited<ReturnType<typeof getUsersMeSessions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMeSessions<TData = Awaited<ReturnType<typeof getUsersMeSessions>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeSessions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List sessions
 */

export function useGetUsersMeSessions<TData = Awaited<ReturnType<typeof getUsersMeSessions>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMeSessions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersMeSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Revoke a specific session for the authenticated user
 * @summary Revoke session
 */
export type deleteUsersMeSessionsIdResponse204 = {
  data: void
  status: 204
}

export type deleteUsersMeSessionsIdResponse401 = {
  data: ErrorBody
  status: 401
}

export type deleteUsersMeSessionsIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteUsersMeSessionsIdResponseSuccess = (deleteUsersMeSessionsIdResponse204) & {
  headers: Headers;
};
export type deleteUsersMeSessionsIdResponseError = (deleteUsersMeSessionsIdResponse401 | deleteUsersMeSessionsIdResponse404) & {
  headers: Headers;
};

export type deleteUsersMeSessionsIdResponse = (deleteUsersMeSessionsIdResponseSuccess | deleteUsersMeSessionsIdResponseError)

export const getDeleteUsersMeSessionsIdUrl = (id: string,) => {




  return `/users/me/sessions/${id}`
}

export const deleteUsersMeSessionsId = async (id: string, options?: RequestInit): Promise<deleteUsersMeSessionsIdResponse> => {

  return apiFetcher<deleteUsersMeSessionsIdResponse>(getDeleteUsersMeSessionsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteUsersMeSessionsIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersMeSessionsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsersMeSessionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteUsersMeSessionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsersMeSessionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteUsersMeSessionsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsersMeSessionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsersMeSessionsId>>>

    export type DeleteUsersMeSessionsIdMutationError = ErrorBody

    /**
 * @summary Revoke session
 */
export const useDeleteUsersMeSessionsId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersMeSessionsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsersMeSessionsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteUsersMeSessionsIdMutationOptions(options), queryClient);
    }
