/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateInviteRequest,
  CreateInviteResponse,
  ErrorBody,
  InviteResponse,
  RedeemInviteRequest,
  RedeemInviteResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * New user redeems an invite token during registration
 * @summary Redeem invite
 */
export type postAuthInvitesRedeemResponse200 = {
  data: RedeemInviteResponse
  status: 200
}

export type postAuthInvitesRedeemResponse400 = {
  data: ErrorBody
  status: 400
}

export type postAuthInvitesRedeemResponse404 = {
  data: ErrorBody
  status: 404
}

export type postAuthInvitesRedeemResponseSuccess = (postAuthInvitesRedeemResponse200) & {
  headers: Headers;
};
export type postAuthInvitesRedeemResponseError = (postAuthInvitesRedeemResponse400 | postAuthInvitesRedeemResponse404) & {
  headers: Headers;
};

export type postAuthInvitesRedeemResponse = (postAuthInvitesRedeemResponseSuccess | postAuthInvitesRedeemResponseError)

export const getPostAuthInvitesRedeemUrl = () => {




  return `/auth/invites/redeem`
}

export const postAuthInvitesRedeem = async (redeemInviteRequest: RedeemInviteRequest, options?: RequestInit): Promise<postAuthInvitesRedeemResponse> => {

  return apiFetcher<postAuthInvitesRedeemResponse>(getPostAuthInvitesRedeemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      redeemInviteRequest,)
  }
);}




export const getPostAuthInvitesRedeemMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthInvitesRedeem>>, TError,{data: RedeemInviteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthInvitesRedeem>>, TError,{data: RedeemInviteRequest}, TContext> => {

const mutationKey = ['postAuthInvitesRedeem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthInvitesRedeem>>, {data: RedeemInviteRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthInvitesRedeem(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthInvitesRedeemMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthInvitesRedeem>>>
    export type PostAuthInvitesRedeemMutationBody = RedeemInviteRequest
    export type PostAuthInvitesRedeemMutationError = ErrorBody

    /**
 * @summary Redeem invite
 */
export const usePostAuthInvitesRedeem = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthInvitesRedeem>>, TError,{data: RedeemInviteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthInvitesRedeem>>,
        TError,
        {data: RedeemInviteRequest},
        TContext
      > => {
      return useMutation(getPostAuthInvitesRedeemMutationOptions(options), queryClient);
    }
    /**
 * Admin lists pending invites for an organization
 * @summary List invites
 */
export type getOrgsIdInvitesResponse200 = {
  data: InviteResponse[]
  status: 200
}

export type getOrgsIdInvitesResponse401 = {
  data: ErrorBody
  status: 401
}

export type getOrgsIdInvitesResponse403 = {
  data: ErrorBody
  status: 403
}

export type getOrgsIdInvitesResponseSuccess = (getOrgsIdInvitesResponse200) & {
  headers: Headers;
};
export type getOrgsIdInvitesResponseError = (getOrgsIdInvitesResponse401 | getOrgsIdInvitesResponse403) & {
  headers: Headers;
};

export type getOrgsIdInvitesResponse = (getOrgsIdInvitesResponseSuccess | getOrgsIdInvitesResponseError)

export const getGetOrgsIdInvitesUrl = (id: string,) => {




  return `/orgs/${id}/invites`
}

export const getOrgsIdInvites = async (id: string, options?: RequestInit): Promise<getOrgsIdInvitesResponse> => {

  return apiFetcher<getOrgsIdInvitesResponse>(getGetOrgsIdInvitesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrgsIdInvitesQueryKey = (id: string,) => {
    return [
    `/orgs/${id}/invites`
    ] as const;
    }


export const getGetOrgsIdInvitesQueryOptions = <TData = Awaited<ReturnType<typeof getOrgsIdInvites>>, TError = ErrorBody>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdInvites>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrgsIdInvitesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrgsIdInvites>>> = ({ signal }) => getOrgsIdInvites(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdInvites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrgsIdInvitesQueryResult = NonNullable<Awaited<ReturnType<typeof getOrgsIdInvites>>>
export type GetOrgsIdInvitesQueryError = ErrorBody


export function useGetOrgsIdInvites<TData = Awaited<ReturnType<typeof getOrgsIdInvites>>, TError = ErrorBody>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdInvites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsIdInvites>>,
          TError,
          Awaited<ReturnType<typeof getOrgsIdInvites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgsIdInvites<TData = Awaited<ReturnType<typeof getOrgsIdInvites>>, TError = ErrorBody>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdInvites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsIdInvites>>,
          TError,
          Awaited<ReturnType<typeof getOrgsIdInvites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrgsIdInvites<TData = Awaited<ReturnType<typeof getOrgsIdInvites>>, TError = ErrorBody>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdInvites>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List invites
 */

export function useGetOrgsIdInvites<TData = Awaited<ReturnType<typeof getOrgsIdInvites>>, TError = ErrorBody>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrgsIdInvites>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrgsIdInvitesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Admin creates an invite token for a new member of the org
 * @summary Create invite
 */
export type postOrgsIdInvitesResponse201 = {
  data: CreateInviteResponse
  status: 201
}

export type postOrgsIdInvitesResponse400 = {
  data: ErrorBody
  status: 400
}

export type postOrgsIdInvitesResponse401 = {
  data: ErrorBody
  status: 401
}

export type postOrgsIdInvitesResponse403 = {
  data: ErrorBody
  status: 403
}

export type postOrgsIdInvitesResponseSuccess = (postOrgsIdInvitesResponse201) & {
  headers: Headers;
};
export type postOrgsIdInvitesResponseError = (postOrgsIdInvitesResponse400 | postOrgsIdInvitesResponse401 | postOrgsIdInvitesResponse403) & {
  headers: Headers;
};

export type postOrgsIdInvitesResponse = (postOrgsIdInvitesResponseSuccess | postOrgsIdInvitesResponseError)

export const getPostOrgsIdInvitesUrl = (id: string,) => {




  return `/orgs/${id}/invites`
}

export const postOrgsIdInvites = async (id: string,
    createInviteRequest: CreateInviteRequest, options?: RequestInit): Promise<postOrgsIdInvitesResponse> => {

  return apiFetcher<postOrgsIdInvitesResponse>(getPostOrgsIdInvitesUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInviteRequest,)
  }
);}




export const getPostOrgsIdInvitesMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrgsIdInvites>>, TError,{id: string;data: CreateInviteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postOrgsIdInvites>>, TError,{id: string;data: CreateInviteRequest}, TContext> => {

const mutationKey = ['postOrgsIdInvites'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrgsIdInvites>>, {id: string;data: CreateInviteRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postOrgsIdInvites(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostOrgsIdInvitesMutationResult = NonNullable<Awaited<ReturnType<typeof postOrgsIdInvites>>>
    export type PostOrgsIdInvitesMutationBody = CreateInviteRequest
    export type PostOrgsIdInvitesMutationError = ErrorBody

    /**
 * @summary Create invite
 */
export const usePostOrgsIdInvites = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrgsIdInvites>>, TError,{id: string;data: CreateInviteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postOrgsIdInvites>>,
        TError,
        {id: string;data: CreateInviteRequest},
        TContext
      > => {
      return useMutation(getPostOrgsIdInvitesMutationOptions(options), queryClient);
    }
    /**
 * Admin revokes a pending org invite by ID
 * @summary Revoke invite
 */
export type deleteOrgsIdInvitesInviteIdResponse204 = {
  data: void
  status: 204
}

export type deleteOrgsIdInvitesInviteIdResponse401 = {
  data: ErrorBody
  status: 401
}

export type deleteOrgsIdInvitesInviteIdResponse403 = {
  data: ErrorBody
  status: 403
}

export type deleteOrgsIdInvitesInviteIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteOrgsIdInvitesInviteIdResponseSuccess = (deleteOrgsIdInvitesInviteIdResponse204) & {
  headers: Headers;
};
export type deleteOrgsIdInvitesInviteIdResponseError = (deleteOrgsIdInvitesInviteIdResponse401 | deleteOrgsIdInvitesInviteIdResponse403 | deleteOrgsIdInvitesInviteIdResponse404) & {
  headers: Headers;
};

export type deleteOrgsIdInvitesInviteIdResponse = (deleteOrgsIdInvitesInviteIdResponseSuccess | deleteOrgsIdInvitesInviteIdResponseError)

export const getDeleteOrgsIdInvitesInviteIdUrl = (id: string,
    inviteId: string,) => {




  return `/orgs/${id}/invites/${inviteId}`
}

export const deleteOrgsIdInvitesInviteId = async (id: string,
    inviteId: string, options?: RequestInit): Promise<deleteOrgsIdInvitesInviteIdResponse> => {

  return apiFetcher<deleteOrgsIdInvitesInviteIdResponse>(getDeleteOrgsIdInvitesInviteIdUrl(id,inviteId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteOrgsIdInvitesInviteIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrgsIdInvitesInviteId>>, TError,{id: string;inviteId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrgsIdInvitesInviteId>>, TError,{id: string;inviteId: string}, TContext> => {

const mutationKey = ['deleteOrgsIdInvitesInviteId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrgsIdInvitesInviteId>>, {id: string;inviteId: string}> = (props) => {
          const {id,inviteId} = props ?? {};

          return  deleteOrgsIdInvitesInviteId(id,inviteId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrgsIdInvitesInviteIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrgsIdInvitesInviteId>>>

    export type DeleteOrgsIdInvitesInviteIdMutationError = ErrorBody

    /**
 * @summary Revoke invite
 */
export const useDeleteOrgsIdInvitesInviteId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrgsIdInvitesInviteId>>, TError,{id: string;inviteId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrgsIdInvitesInviteId>>,
        TError,
        {id: string;inviteId: string},
        TContext
      > => {
      return useMutation(getDeleteOrgsIdInvitesInviteIdMutationOptions(options), queryClient);
    }
