/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateInviteRequest,
  CreateInviteResponse,
  ErrorBody,
  GetInvitesParams,
  InviteResponse,
  RedeemInviteRequest,
  RedeemInviteResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Admin lists pending invites for an organization
 * @summary List invites
 */
export type getInvitesResponse200 = {
  data: InviteResponse[]
  status: 200
}

export type getInvitesResponse401 = {
  data: ErrorBody
  status: 401
}

export type getInvitesResponse403 = {
  data: ErrorBody
  status: 403
}

export type getInvitesResponseSuccess = (getInvitesResponse200) & {
  headers: Headers;
};
export type getInvitesResponseError = (getInvitesResponse401 | getInvitesResponse403) & {
  headers: Headers;
};

export type getInvitesResponse = (getInvitesResponseSuccess | getInvitesResponseError)

export const getGetInvitesUrl = (params: GetInvitesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/invites?${stringifiedParams}` : `/invites`
}

export const getInvites = async (params: GetInvitesParams, options?: RequestInit): Promise<getInvitesResponse> => {

  return apiFetcher<getInvitesResponse>(getGetInvitesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInvitesQueryKey = (params?: GetInvitesParams,) => {
    return [
    `/invites`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetInvitesQueryOptions = <TData = Awaited<ReturnType<typeof getInvites>>, TError = ErrorBody>(params: GetInvitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvites>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInvitesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvites>>> = ({ signal }) => getInvites(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInvites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInvitesQueryResult = NonNullable<Awaited<ReturnType<typeof getInvites>>>
export type GetInvitesQueryError = ErrorBody


export function useGetInvites<TData = Awaited<ReturnType<typeof getInvites>>, TError = ErrorBody>(
 params: GetInvitesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvites>>,
          TError,
          Awaited<ReturnType<typeof getInvites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInvites<TData = Awaited<ReturnType<typeof getInvites>>, TError = ErrorBody>(
 params: GetInvitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvites>>,
          TError,
          Awaited<ReturnType<typeof getInvites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInvites<TData = Awaited<ReturnType<typeof getInvites>>, TError = ErrorBody>(
 params: GetInvitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvites>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List invites
 */

export function useGetInvites<TData = Awaited<ReturnType<typeof getInvites>>, TError = ErrorBody>(
 params: GetInvitesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvites>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInvitesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Admin creates an invite token for a new member
 * @summary Create invite
 */
export type postInvitesResponse201 = {
  data: CreateInviteResponse
  status: 201
}

export type postInvitesResponse400 = {
  data: ErrorBody
  status: 400
}

export type postInvitesResponse401 = {
  data: ErrorBody
  status: 401
}

export type postInvitesResponse403 = {
  data: ErrorBody
  status: 403
}

export type postInvitesResponseSuccess = (postInvitesResponse201) & {
  headers: Headers;
};
export type postInvitesResponseError = (postInvitesResponse400 | postInvitesResponse401 | postInvitesResponse403) & {
  headers: Headers;
};

export type postInvitesResponse = (postInvitesResponseSuccess | postInvitesResponseError)

export const getPostInvitesUrl = () => {




  return `/invites`
}

export const postInvites = async (createInviteRequest: CreateInviteRequest, options?: RequestInit): Promise<postInvitesResponse> => {

  return apiFetcher<postInvitesResponse>(getPostInvitesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInviteRequest,)
  }
);}




export const getPostInvitesMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInvites>>, TError,{data: CreateInviteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postInvites>>, TError,{data: CreateInviteRequest}, TContext> => {

const mutationKey = ['postInvites'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInvites>>, {data: CreateInviteRequest}> = (props) => {
          const {data} = props ?? {};

          return  postInvites(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInvitesMutationResult = NonNullable<Awaited<ReturnType<typeof postInvites>>>
    export type PostInvitesMutationBody = CreateInviteRequest
    export type PostInvitesMutationError = ErrorBody

    /**
 * @summary Create invite
 */
export const usePostInvites = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInvites>>, TError,{data: CreateInviteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInvites>>,
        TError,
        {data: CreateInviteRequest},
        TContext
      > => {
      return useMutation(getPostInvitesMutationOptions(options), queryClient);
    }
    /**
 * New user redeems an invite token during registration
 * @summary Redeem invite
 */
export type postInvitesRedeemResponse200 = {
  data: RedeemInviteResponse
  status: 200
}

export type postInvitesRedeemResponse400 = {
  data: ErrorBody
  status: 400
}

export type postInvitesRedeemResponse404 = {
  data: ErrorBody
  status: 404
}

export type postInvitesRedeemResponseSuccess = (postInvitesRedeemResponse200) & {
  headers: Headers;
};
export type postInvitesRedeemResponseError = (postInvitesRedeemResponse400 | postInvitesRedeemResponse404) & {
  headers: Headers;
};

export type postInvitesRedeemResponse = (postInvitesRedeemResponseSuccess | postInvitesRedeemResponseError)

export const getPostInvitesRedeemUrl = () => {




  return `/invites/redeem`
}

export const postInvitesRedeem = async (redeemInviteRequest: RedeemInviteRequest, options?: RequestInit): Promise<postInvitesRedeemResponse> => {

  return apiFetcher<postInvitesRedeemResponse>(getPostInvitesRedeemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      redeemInviteRequest,)
  }
);}




export const getPostInvitesRedeemMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInvitesRedeem>>, TError,{data: RedeemInviteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postInvitesRedeem>>, TError,{data: RedeemInviteRequest}, TContext> => {

const mutationKey = ['postInvitesRedeem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInvitesRedeem>>, {data: RedeemInviteRequest}> = (props) => {
          const {data} = props ?? {};

          return  postInvitesRedeem(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostInvitesRedeemMutationResult = NonNullable<Awaited<ReturnType<typeof postInvitesRedeem>>>
    export type PostInvitesRedeemMutationBody = RedeemInviteRequest
    export type PostInvitesRedeemMutationError = ErrorBody

    /**
 * @summary Redeem invite
 */
export const usePostInvitesRedeem = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInvitesRedeem>>, TError,{data: RedeemInviteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInvitesRedeem>>,
        TError,
        {data: RedeemInviteRequest},
        TContext
      > => {
      return useMutation(getPostInvitesRedeemMutationOptions(options), queryClient);
    }
    /**
 * Admin revokes a pending invite by ID
 * @summary Revoke invite
 */
export type deleteInvitesIdResponse204 = {
  data: void
  status: 204
}

export type deleteInvitesIdResponse401 = {
  data: ErrorBody
  status: 401
}

export type deleteInvitesIdResponse403 = {
  data: ErrorBody
  status: 403
}

export type deleteInvitesIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteInvitesIdResponseSuccess = (deleteInvitesIdResponse204) & {
  headers: Headers;
};
export type deleteInvitesIdResponseError = (deleteInvitesIdResponse401 | deleteInvitesIdResponse403 | deleteInvitesIdResponse404) & {
  headers: Headers;
};

export type deleteInvitesIdResponse = (deleteInvitesIdResponseSuccess | deleteInvitesIdResponseError)

export const getDeleteInvitesIdUrl = (id: string,) => {




  return `/invites/${id}`
}

export const deleteInvitesId = async (id: string, options?: RequestInit): Promise<deleteInvitesIdResponse> => {

  return apiFetcher<deleteInvitesIdResponse>(getDeleteInvitesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteInvitesIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteInvitesId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteInvitesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteInvitesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteInvitesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteInvitesId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteInvitesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteInvitesId>>>

    export type DeleteInvitesIdMutationError = ErrorBody

    /**
 * @summary Revoke invite
 */
export const useDeleteInvitesId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteInvitesId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteInvitesId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteInvitesIdMutationOptions(options), queryClient);
    }
