/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  GetAuthPreloginParams,
  LoginRequest,
  LoginResponse,
  LogoutRequest,
  PasswordChangeRequest,
  PasswordChangeResponse,
  PreloginResponse,
  RefreshRequest,
  RefreshResponse,
  RegisterRequest,
  RegisterResponse,
  StepUpRequest,
  StepUpResponse,
  TOTPCodeRequest,
  TOTPSetupResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Authenticate with email and auth hash, returns JWT tokens and encrypted crypto material
 * @summary Login
 */
export type postAuthLoginResponse200 = {
  data: LoginResponse
  status: 200
}

export type postAuthLoginResponse401 = {
  data: ErrorBody
  status: 401
}

export type postAuthLoginResponse423 = {
  data: ErrorBody
  status: 423
}

export type postAuthLoginResponse429 = {
  data: ErrorBody
  status: 429
}

export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse401 | postAuthLoginResponse423 | postAuthLoginResponse429) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {




  return `/auth/login`
}

export const postAuthLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<postAuthLoginResponse> => {

  return apiFetcher<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}




export const getPostAuthLoginMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = LoginRequest
    export type PostAuthLoginMutationError = ErrorBody

    /**
 * @summary Login
 */
export const usePostAuthLogin = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
    }
    /**
 * Revoke the refresh token to end the session
 * @summary Logout
 */
export type postAuthLogoutResponse204 = {
  data: void
  status: 204
}

export type postAuthLogoutResponse401 = {
  data: ErrorBody
  status: 401
}

export type postAuthLogoutResponseSuccess = (postAuthLogoutResponse204) & {
  headers: Headers;
};
export type postAuthLogoutResponseError = (postAuthLogoutResponse401) & {
  headers: Headers;
};

export type postAuthLogoutResponse = (postAuthLogoutResponseSuccess | postAuthLogoutResponseError)

export const getPostAuthLogoutUrl = () => {




  return `/auth/logout`
}

export const postAuthLogout = async (logoutRequest: LogoutRequest, options?: RequestInit): Promise<postAuthLogoutResponse> => {

  return apiFetcher<postAuthLogoutResponse>(getPostAuthLogoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      logoutRequest,)
  }
);}




export const getPostAuthLogoutMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: LogoutRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: LogoutRequest}, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, {data: LogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogout(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>
    export type PostAuthLogoutMutationBody = LogoutRequest
    export type PostAuthLogoutMutationError = ErrorBody

    /**
 * @summary Logout
 */
export const usePostAuthLogout = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: LogoutRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        {data: LogoutRequest},
        TContext
      > => {
      return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
    }
    /**
 * Change master password and re-encrypt private keys. Requires step-up.
 * @summary Change master password
 */
export type postAuthPasswordChangeResponse200 = {
  data: PasswordChangeResponse
  status: 200
}

export type postAuthPasswordChangeResponse401 = {
  data: ErrorBody
  status: 401
}

export type postAuthPasswordChangeResponse403 = {
  data: ErrorBody
  status: 403
}

export type postAuthPasswordChangeResponseSuccess = (postAuthPasswordChangeResponse200) & {
  headers: Headers;
};
export type postAuthPasswordChangeResponseError = (postAuthPasswordChangeResponse401 | postAuthPasswordChangeResponse403) & {
  headers: Headers;
};

export type postAuthPasswordChangeResponse = (postAuthPasswordChangeResponseSuccess | postAuthPasswordChangeResponseError)

export const getPostAuthPasswordChangeUrl = () => {




  return `/auth/password/change`
}

export const postAuthPasswordChange = async (passwordChangeRequest: PasswordChangeRequest, options?: RequestInit): Promise<postAuthPasswordChangeResponse> => {

  return apiFetcher<postAuthPasswordChangeResponse>(getPostAuthPasswordChangeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passwordChangeRequest,)
  }
);}




export const getPostAuthPasswordChangeMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthPasswordChange>>, TError,{data: PasswordChangeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthPasswordChange>>, TError,{data: PasswordChangeRequest}, TContext> => {

const mutationKey = ['postAuthPasswordChange'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthPasswordChange>>, {data: PasswordChangeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthPasswordChange(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthPasswordChangeMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthPasswordChange>>>
    export type PostAuthPasswordChangeMutationBody = PasswordChangeRequest
    export type PostAuthPasswordChangeMutationError = ErrorBody

    /**
 * @summary Change master password
 */
export const usePostAuthPasswordChange = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthPasswordChange>>, TError,{data: PasswordChangeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthPasswordChange>>,
        TError,
        {data: PasswordChangeRequest},
        TContext
      > => {
      return useMutation(getPostAuthPasswordChangeMutationOptions(options), queryClient);
    }
    /**
 * Returns salt and KDF parameters needed to derive the auth hash client-side
 * @summary Get KDF parameters
 */
export type getAuthPreloginResponse200 = {
  data: PreloginResponse
  status: 200
}

export type getAuthPreloginResponse404 = {
  data: ErrorBody
  status: 404
}

export type getAuthPreloginResponseSuccess = (getAuthPreloginResponse200) & {
  headers: Headers;
};
export type getAuthPreloginResponseError = (getAuthPreloginResponse404) & {
  headers: Headers;
};

export type getAuthPreloginResponse = (getAuthPreloginResponseSuccess | getAuthPreloginResponseError)

export const getGetAuthPreloginUrl = (params: GetAuthPreloginParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/prelogin?${stringifiedParams}` : `/auth/prelogin`
}

export const getAuthPrelogin = async (params: GetAuthPreloginParams, options?: RequestInit): Promise<getAuthPreloginResponse> => {

  return apiFetcher<getAuthPreloginResponse>(getGetAuthPreloginUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthPreloginQueryKey = (params?: GetAuthPreloginParams,) => {
    return [
    `/auth/prelogin`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuthPreloginQueryOptions = <TData = Awaited<ReturnType<typeof getAuthPrelogin>>, TError = ErrorBody>(params: GetAuthPreloginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthPrelogin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthPreloginQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthPrelogin>>> = ({ signal }) => getAuthPrelogin(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthPrelogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthPreloginQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthPrelogin>>>
export type GetAuthPreloginQueryError = ErrorBody


export function useGetAuthPrelogin<TData = Awaited<ReturnType<typeof getAuthPrelogin>>, TError = ErrorBody>(
 params: GetAuthPreloginParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthPrelogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthPrelogin>>,
          TError,
          Awaited<ReturnType<typeof getAuthPrelogin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthPrelogin<TData = Awaited<ReturnType<typeof getAuthPrelogin>>, TError = ErrorBody>(
 params: GetAuthPreloginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthPrelogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthPrelogin>>,
          TError,
          Awaited<ReturnType<typeof getAuthPrelogin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthPrelogin<TData = Awaited<ReturnType<typeof getAuthPrelogin>>, TError = ErrorBody>(
 params: GetAuthPreloginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthPrelogin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get KDF parameters
 */

export function useGetAuthPrelogin<TData = Awaited<ReturnType<typeof getAuthPrelogin>>, TError = ErrorBody>(
 params: GetAuthPreloginParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthPrelogin>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthPreloginQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Exchange a valid refresh token for a new access/refresh token pair
 * @summary Refresh tokens
 */
export type postAuthRefreshResponse200 = {
  data: RefreshResponse
  status: 200
}

export type postAuthRefreshResponse401 = {
  data: ErrorBody
  status: 401
}

export type postAuthRefreshResponseSuccess = (postAuthRefreshResponse200) & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (postAuthRefreshResponse401) & {
  headers: Headers;
};

export type postAuthRefreshResponse = (postAuthRefreshResponseSuccess | postAuthRefreshResponseError)

export const getPostAuthRefreshUrl = () => {




  return `/auth/refresh`
}

export const postAuthRefresh = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<postAuthRefreshResponse> => {

  return apiFetcher<postAuthRefreshResponse>(getPostAuthRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshRequest,)
  }
);}




export const getPostAuthRefreshMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: RefreshRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: RefreshRequest}, TContext> => {

const mutationKey = ['postAuthRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, {data: RefreshRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRefresh(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRefresh>>>
    export type PostAuthRefreshMutationBody = RefreshRequest
    export type PostAuthRefreshMutationError = ErrorBody

    /**
 * @summary Refresh tokens
 */
export const usePostAuthRefresh = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: RefreshRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRefresh>>,
        TError,
        {data: RefreshRequest},
        TContext
      > => {
      return useMutation(getPostAuthRefreshMutationOptions(options), queryClient);
    }
    /**
 * Create a new user account with client-side derived crypto material
 * @summary Register new user
 */
export type postAuthRegisterResponse201 = {
  data: RegisterResponse
  status: 201
}

export type postAuthRegisterResponse400 = {
  data: ErrorBody
  status: 400
}

export type postAuthRegisterResponse409 = {
  data: ErrorBody
  status: 409
}

export type postAuthRegisterResponse429 = {
  data: ErrorBody
  status: 429
}

export type postAuthRegisterResponseSuccess = (postAuthRegisterResponse201) & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (postAuthRegisterResponse400 | postAuthRegisterResponse409 | postAuthRegisterResponse429) & {
  headers: Headers;
};

export type postAuthRegisterResponse = (postAuthRegisterResponseSuccess | postAuthRegisterResponseError)

export const getPostAuthRegisterUrl = () => {




  return `/auth/register`
}

export const postAuthRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<postAuthRegisterResponse> => {

  return apiFetcher<postAuthRegisterResponse>(getPostAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}




export const getPostAuthRegisterMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: RegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = RegisterRequest
    export type PostAuthRegisterMutationError = ErrorBody

    /**
 * @summary Register new user
 */
export const usePostAuthRegister = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: RegisterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getPostAuthRegisterMutationOptions(options), queryClient);
    }
    /**
 * Re-verify master password to get a step-up token for sensitive operations
 * @summary Step-up authentication
 */
export type postAuthStepUpResponse200 = {
  data: StepUpResponse
  status: 200
}

export type postAuthStepUpResponse401 = {
  data: ErrorBody
  status: 401
}

export type postAuthStepUpResponse429 = {
  data: ErrorBody
  status: 429
}

export type postAuthStepUpResponseSuccess = (postAuthStepUpResponse200) & {
  headers: Headers;
};
export type postAuthStepUpResponseError = (postAuthStepUpResponse401 | postAuthStepUpResponse429) & {
  headers: Headers;
};

export type postAuthStepUpResponse = (postAuthStepUpResponseSuccess | postAuthStepUpResponseError)

export const getPostAuthStepUpUrl = () => {




  return `/auth/step-up`
}

export const postAuthStepUp = async (stepUpRequest: StepUpRequest, options?: RequestInit): Promise<postAuthStepUpResponse> => {

  return apiFetcher<postAuthStepUpResponse>(getPostAuthStepUpUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      stepUpRequest,)
  }
);}




export const getPostAuthStepUpMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthStepUp>>, TError,{data: StepUpRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthStepUp>>, TError,{data: StepUpRequest}, TContext> => {

const mutationKey = ['postAuthStepUp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthStepUp>>, {data: StepUpRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthStepUp(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthStepUpMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthStepUp>>>
    export type PostAuthStepUpMutationBody = StepUpRequest
    export type PostAuthStepUpMutationError = ErrorBody

    /**
 * @summary Step-up authentication
 */
export const usePostAuthStepUp = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthStepUp>>, TError,{data: StepUpRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthStepUp>>,
        TError,
        {data: StepUpRequest},
        TContext
      > => {
      return useMutation(getPostAuthStepUpMutationOptions(options), queryClient);
    }
    /**
 * Deactivate two-factor authentication. Requires step-up.
 * @summary Disable TOTP 2FA
 */
export type postAuthTotpDisableResponse204 = {
  data: void
  status: 204
}

export type postAuthTotpDisableResponse403 = {
  data: ErrorBody
  status: 403
}

export type postAuthTotpDisableResponseSuccess = (postAuthTotpDisableResponse204) & {
  headers: Headers;
};
export type postAuthTotpDisableResponseError = (postAuthTotpDisableResponse403) & {
  headers: Headers;
};

export type postAuthTotpDisableResponse = (postAuthTotpDisableResponseSuccess | postAuthTotpDisableResponseError)

export const getPostAuthTotpDisableUrl = () => {




  return `/auth/totp/disable`
}

export const postAuthTotpDisable = async ( options?: RequestInit): Promise<postAuthTotpDisableResponse> => {

  return apiFetcher<postAuthTotpDisableResponse>(getPostAuthTotpDisableUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthTotpDisableMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpDisable>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpDisable>>, TError,void, TContext> => {

const mutationKey = ['postAuthTotpDisable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthTotpDisable>>, void> = () => {


          return  postAuthTotpDisable()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthTotpDisableMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthTotpDisable>>>

    export type PostAuthTotpDisableMutationError = ErrorBody

    /**
 * @summary Disable TOTP 2FA
 */
export const usePostAuthTotpDisable = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpDisable>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthTotpDisable>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthTotpDisableMutationOptions(options), queryClient);
    }
    /**
 * Verify a TOTP code to activate two-factor authentication
 * @summary Enable TOTP 2FA
 */
export type postAuthTotpEnableResponse204 = {
  data: void
  status: 204
}

export type postAuthTotpEnableResponse400 = {
  data: ErrorBody
  status: 400
}

export type postAuthTotpEnableResponseSuccess = (postAuthTotpEnableResponse204) & {
  headers: Headers;
};
export type postAuthTotpEnableResponseError = (postAuthTotpEnableResponse400) & {
  headers: Headers;
};

export type postAuthTotpEnableResponse = (postAuthTotpEnableResponseSuccess | postAuthTotpEnableResponseError)

export const getPostAuthTotpEnableUrl = () => {




  return `/auth/totp/enable`
}

export const postAuthTotpEnable = async (tOTPCodeRequest: TOTPCodeRequest, options?: RequestInit): Promise<postAuthTotpEnableResponse> => {

  return apiFetcher<postAuthTotpEnableResponse>(getPostAuthTotpEnableUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tOTPCodeRequest,)
  }
);}




export const getPostAuthTotpEnableMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpEnable>>, TError,{data: TOTPCodeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpEnable>>, TError,{data: TOTPCodeRequest}, TContext> => {

const mutationKey = ['postAuthTotpEnable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthTotpEnable>>, {data: TOTPCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthTotpEnable(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthTotpEnableMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthTotpEnable>>>
    export type PostAuthTotpEnableMutationBody = TOTPCodeRequest
    export type PostAuthTotpEnableMutationError = ErrorBody

    /**
 * @summary Enable TOTP 2FA
 */
export const usePostAuthTotpEnable = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpEnable>>, TError,{data: TOTPCodeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthTotpEnable>>,
        TError,
        {data: TOTPCodeRequest},
        TContext
      > => {
      return useMutation(getPostAuthTotpEnableMutationOptions(options), queryClient);
    }
    /**
 * Generate a new TOTP secret and QR code URL. Requires step-up authentication.
 * @summary Setup TOTP 2FA
 */
export type postAuthTotpSetupResponse200 = {
  data: TOTPSetupResponse
  status: 200
}

export type postAuthTotpSetupResponse403 = {
  data: ErrorBody
  status: 403
}

export type postAuthTotpSetupResponseSuccess = (postAuthTotpSetupResponse200) & {
  headers: Headers;
};
export type postAuthTotpSetupResponseError = (postAuthTotpSetupResponse403) & {
  headers: Headers;
};

export type postAuthTotpSetupResponse = (postAuthTotpSetupResponseSuccess | postAuthTotpSetupResponseError)

export const getPostAuthTotpSetupUrl = () => {




  return `/auth/totp/setup`
}

export const postAuthTotpSetup = async ( options?: RequestInit): Promise<postAuthTotpSetupResponse> => {

  return apiFetcher<postAuthTotpSetupResponse>(getPostAuthTotpSetupUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthTotpSetupMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpSetup>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpSetup>>, TError,void, TContext> => {

const mutationKey = ['postAuthTotpSetup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthTotpSetup>>, void> = () => {


          return  postAuthTotpSetup()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthTotpSetupMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthTotpSetup>>>

    export type PostAuthTotpSetupMutationError = ErrorBody

    /**
 * @summary Setup TOTP 2FA
 */
export const usePostAuthTotpSetup = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpSetup>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthTotpSetup>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthTotpSetupMutationOptions(options), queryClient);
    }
    /**
 * Validate a TOTP code during the two-factor authentication step of login
 * @summary Verify TOTP code
 */
export type postAuthTotpVerifyResponse204 = {
  data: void
  status: 204
}

export type postAuthTotpVerifyResponse400 = {
  data: ErrorBody
  status: 400
}

export type postAuthTotpVerifyResponseSuccess = (postAuthTotpVerifyResponse204) & {
  headers: Headers;
};
export type postAuthTotpVerifyResponseError = (postAuthTotpVerifyResponse400) & {
  headers: Headers;
};

export type postAuthTotpVerifyResponse = (postAuthTotpVerifyResponseSuccess | postAuthTotpVerifyResponseError)

export const getPostAuthTotpVerifyUrl = () => {




  return `/auth/totp/verify`
}

export const postAuthTotpVerify = async (tOTPCodeRequest: TOTPCodeRequest, options?: RequestInit): Promise<postAuthTotpVerifyResponse> => {

  return apiFetcher<postAuthTotpVerifyResponse>(getPostAuthTotpVerifyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tOTPCodeRequest,)
  }
);}




export const getPostAuthTotpVerifyMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpVerify>>, TError,{data: TOTPCodeRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpVerify>>, TError,{data: TOTPCodeRequest}, TContext> => {

const mutationKey = ['postAuthTotpVerify'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthTotpVerify>>, {data: TOTPCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthTotpVerify(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthTotpVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthTotpVerify>>>
    export type PostAuthTotpVerifyMutationBody = TOTPCodeRequest
    export type PostAuthTotpVerifyMutationError = ErrorBody

    /**
 * @summary Verify TOTP code
 */
export const usePostAuthTotpVerify = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthTotpVerify>>, TError,{data: TOTPCodeRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthTotpVerify>>,
        TError,
        {data: TOTPCodeRequest},
        TContext
      > => {
      return useMutation(getPostAuthTotpVerifyMutationOptions(options), queryClient);
    }
