/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  ListBackupsResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * Backup requires pg_dump (shell access) and is not suitable for HTTP API. Use the CLI instead.
 * @summary Trigger backup
 */
export type postAdminBackupResponse501 = {
  data: ErrorBody
  status: 501
}

;
export type postAdminBackupResponseError = (postAdminBackupResponse501) & {
  headers: Headers;
};

export type postAdminBackupResponse = (postAdminBackupResponseError)

export const getPostAdminBackupUrl = () => {




  return `/admin/backup`
}

export const postAdminBackup = async ( options?: RequestInit): Promise<postAdminBackupResponse> => {

  return apiFetcher<postAdminBackupResponse>(getPostAdminBackupUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAdminBackupMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminBackup>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAdminBackup>>, TError,void, TContext> => {

const mutationKey = ['postAdminBackup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminBackup>>, void> = () => {


          return  postAdminBackup()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminBackupMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminBackup>>>

    export type PostAdminBackupMutationError = ErrorBody

    /**
 * @summary Trigger backup
 */
export const usePostAdminBackup = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminBackup>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAdminBackup>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAdminBackupMutationOptions(options), queryClient);
    }
    /**
 * List available backup files with size and creation time. Admin only.
 * @summary List backups
 */
export type getAdminBackupsResponse200 = {
  data: ListBackupsResponse
  status: 200
}

export type getAdminBackupsResponse401 = {
  data: ErrorBody
  status: 401
}

export type getAdminBackupsResponse403 = {
  data: ErrorBody
  status: 403
}

export type getAdminBackupsResponseSuccess = (getAdminBackupsResponse200) & {
  headers: Headers;
};
export type getAdminBackupsResponseError = (getAdminBackupsResponse401 | getAdminBackupsResponse403) & {
  headers: Headers;
};

export type getAdminBackupsResponse = (getAdminBackupsResponseSuccess | getAdminBackupsResponseError)

export const getGetAdminBackupsUrl = () => {




  return `/admin/backups`
}

export const getAdminBackups = async ( options?: RequestInit): Promise<getAdminBackupsResponse> => {

  return apiFetcher<getAdminBackupsResponse>(getGetAdminBackupsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminBackupsQueryKey = () => {
    return [
    `/admin/backups`
    ] as const;
    }


export const getGetAdminBackupsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminBackups>>, TError = ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBackups>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminBackupsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminBackups>>> = ({ signal }) => getAdminBackups({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminBackups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdminBackupsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminBackups>>>
export type GetAdminBackupsQueryError = ErrorBody


export function useGetAdminBackups<TData = Awaited<ReturnType<typeof getAdminBackups>>, TError = ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBackups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminBackups>>,
          TError,
          Awaited<ReturnType<typeof getAdminBackups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminBackups<TData = Awaited<ReturnType<typeof getAdminBackups>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBackups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdminBackups>>,
          TError,
          Awaited<ReturnType<typeof getAdminBackups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdminBackups<TData = Awaited<ReturnType<typeof getAdminBackups>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBackups>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List backups
 */

export function useGetAdminBackups<TData = Awaited<ReturnType<typeof getAdminBackups>>, TError = ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdminBackups>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAdminBackupsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




