// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Crypto interop tests: verifies that the shared TS crypto helpers produce
 * byte-identical output to the fixtures generated by the web build and
 * verified against the Go backend.
 *
 * Fixtures live at: testdata/crypto/{hkdf,aes_gcm}_fixtures.json
 *
 * The argon2id step is excluded because react-native-argon2 requires native bindings.
 */

import { readFileSync } from 'fs';
import { join } from 'path';
import { webcrypto } from 'crypto';

import { deriveAuthHash, deriveStretchedKey } from '@vaultctl/shared/crypto/hkdf';
import { aesGcmEncrypt, aesGcmDecrypt } from '@vaultctl/shared/crypto/aes-gcm';
import { parseBlob } from '@vaultctl/shared/crypto/blob';

// Polyfill globalThis.crypto for the shared HKDF/AES-GCM code (Node 18+)
if (!globalThis.crypto) {
  // @ts-expect-error node webcrypto polyfill
  globalThis.crypto = webcrypto;
}

const FIXTURE_DIR = join(__dirname, '../../../testdata/crypto');

interface HkdfFixture {
  master_key_b64: string;
  auth_hash_b64: string;
  stretched_key_b64: string;
}

interface AesGcmFixture {
  key_b64: string;
  plaintext_b64: string;
  blob_b64: string;
  aad_b64?: string;
}

function fromBase64(b64: string): Uint8Array {
  return Uint8Array.from(Buffer.from(b64, 'base64'));
}

function toBase64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('base64');
}

const hkdfFixtures: HkdfFixture[] = JSON.parse(
  readFileSync(join(FIXTURE_DIR, 'hkdf_fixtures.json'), 'utf-8'),
);

const aesGcmFixtures: AesGcmFixture[] = JSON.parse(
  readFileSync(join(FIXTURE_DIR, 'aes_gcm_fixtures.json'), 'utf-8'),
);

describe('HKDF interop', () => {
  it.each(hkdfFixtures)(
    'derives auth hash and stretched key ($master_key_b64)',
    async (fixture) => {
      const masterKey = fromBase64(fixture.master_key_b64);
      const [authHash, stretchedKey] = await Promise.all([
        deriveAuthHash(masterKey),
        deriveStretchedKey(masterKey),
      ]);

      expect(toBase64(authHash)).toBe(fixture.auth_hash_b64);
      expect(toBase64(stretchedKey)).toBe(fixture.stretched_key_b64);
    },
  );
});

describe('AES-GCM interop', () => {
  it.each(aesGcmFixtures)(
    'decrypts fixture blob to expected plaintext ($key_b64)',
    async (fixture) => {
      const key = fromBase64(fixture.key_b64);
      const blob = parseBlob(fromBase64(fixture.blob_b64));
      const aad = fixture.aad_b64 ? fromBase64(fixture.aad_b64) : undefined;

      const plaintext = await aesGcmDecrypt(key, blob, aad);
      expect(toBase64(plaintext)).toBe(fixture.plaintext_b64);
    },
  );

  it.each(aesGcmFixtures)(
    'round-trip: encrypt then decrypt recovers plaintext ($key_b64)',
    async (fixture) => {
      const key = fromBase64(fixture.key_b64);
      const plaintext = fromBase64(fixture.plaintext_b64);
      const aad = fixture.aad_b64 ? fromBase64(fixture.aad_b64) : undefined;

      const encryptedBlob = await aesGcmEncrypt(key, plaintext, aad);
      const decrypted = await aesGcmDecrypt(key, encryptedBlob, aad);

      expect(toBase64(decrypted)).toBe(fixture.plaintext_b64);
    },
  );
});
