/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * vaultctl API
 * Zero-knowledge, self-hosted password vault API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  ItemResponse
} from '../model';

import { apiFetcher } from '../../lib/api-fetcher';




/**
 * List all soft-deleted items in a vault
 * @summary List trash
 */
export type getVaultsVaultIdTrashResponse200 = {
  data: ItemResponse[]
  status: 200
}

export type getVaultsVaultIdTrashResponse404 = {
  data: ErrorBody
  status: 404
}

export type getVaultsVaultIdTrashResponseSuccess = (getVaultsVaultIdTrashResponse200) & {
  headers: Headers;
};
export type getVaultsVaultIdTrashResponseError = (getVaultsVaultIdTrashResponse404) & {
  headers: Headers;
};

export type getVaultsVaultIdTrashResponse = (getVaultsVaultIdTrashResponseSuccess | getVaultsVaultIdTrashResponseError)

export const getGetVaultsVaultIdTrashUrl = (vaultId: string,) => {




  return `/vaults/${vaultId}/trash`
}

export const getVaultsVaultIdTrash = async (vaultId: string, options?: RequestInit): Promise<getVaultsVaultIdTrashResponse> => {

  return apiFetcher<getVaultsVaultIdTrashResponse>(getGetVaultsVaultIdTrashUrl(vaultId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetVaultsVaultIdTrashQueryKey = (vaultId: string,) => {
    return [
    `/vaults/${vaultId}/trash`
    ] as const;
    }


export const getGetVaultsVaultIdTrashQueryOptions = <TData = Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError = ErrorBody>(vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVaultsVaultIdTrashQueryKey(vaultId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>> = ({ signal }) => getVaultsVaultIdTrash(vaultId, { signal });





   return  { queryKey, queryFn, enabled: !!(vaultId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVaultsVaultIdTrashQueryResult = NonNullable<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>>
export type GetVaultsVaultIdTrashQueryError = ErrorBody


export function useGetVaultsVaultIdTrash<TData = Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError = ErrorBody>(
 vaultId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdTrash>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdTrash>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdTrash<TData = Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError = ErrorBody>(
 vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVaultsVaultIdTrash>>,
          TError,
          Awaited<ReturnType<typeof getVaultsVaultIdTrash>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVaultsVaultIdTrash<TData = Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError = ErrorBody>(
 vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List trash
 */

export function useGetVaultsVaultIdTrash<TData = Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError = ErrorBody>(
 vaultId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVaultsVaultIdTrash>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVaultsVaultIdTrashQueryOptions(vaultId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Permanently delete a trashed item. Requires step-up authentication.
 * @summary Purge item
 */
export type deleteVaultsVaultIdTrashIdResponse204 = {
  data: void
  status: 204
}

export type deleteVaultsVaultIdTrashIdResponse403 = {
  data: ErrorBody
  status: 403
}

export type deleteVaultsVaultIdTrashIdResponse404 = {
  data: ErrorBody
  status: 404
}

export type deleteVaultsVaultIdTrashIdResponseSuccess = (deleteVaultsVaultIdTrashIdResponse204) & {
  headers: Headers;
};
export type deleteVaultsVaultIdTrashIdResponseError = (deleteVaultsVaultIdTrashIdResponse403 | deleteVaultsVaultIdTrashIdResponse404) & {
  headers: Headers;
};

export type deleteVaultsVaultIdTrashIdResponse = (deleteVaultsVaultIdTrashIdResponseSuccess | deleteVaultsVaultIdTrashIdResponseError)

export const getDeleteVaultsVaultIdTrashIdUrl = (vaultId: string,
    id: string,) => {




  return `/vaults/${vaultId}/trash/${id}`
}

export const deleteVaultsVaultIdTrashId = async (vaultId: string,
    id: string, options?: RequestInit): Promise<deleteVaultsVaultIdTrashIdResponse> => {

  return apiFetcher<deleteVaultsVaultIdTrashIdResponse>(getDeleteVaultsVaultIdTrashIdUrl(vaultId,id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteVaultsVaultIdTrashIdMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdTrashId>>, TError,{vaultId: string;id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdTrashId>>, TError,{vaultId: string;id: string}, TContext> => {

const mutationKey = ['deleteVaultsVaultIdTrashId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVaultsVaultIdTrashId>>, {vaultId: string;id: string}> = (props) => {
          const {vaultId,id} = props ?? {};

          return  deleteVaultsVaultIdTrashId(vaultId,id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteVaultsVaultIdTrashIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVaultsVaultIdTrashId>>>

    export type DeleteVaultsVaultIdTrashIdMutationError = ErrorBody

    /**
 * @summary Purge item
 */
export const useDeleteVaultsVaultIdTrashId = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVaultsVaultIdTrashId>>, TError,{vaultId: string;id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVaultsVaultIdTrashId>>,
        TError,
        {vaultId: string;id: string},
        TContext
      > => {
      return useMutation(getDeleteVaultsVaultIdTrashIdMutationOptions(options), queryClient);
    }
    /**
 * Restore a soft-deleted item from trash
 * @summary Restore item
 */
export type postVaultsVaultIdTrashIdRestoreResponse204 = {
  data: void
  status: 204
}

export type postVaultsVaultIdTrashIdRestoreResponse404 = {
  data: ErrorBody
  status: 404
}

export type postVaultsVaultIdTrashIdRestoreResponseSuccess = (postVaultsVaultIdTrashIdRestoreResponse204) & {
  headers: Headers;
};
export type postVaultsVaultIdTrashIdRestoreResponseError = (postVaultsVaultIdTrashIdRestoreResponse404) & {
  headers: Headers;
};

export type postVaultsVaultIdTrashIdRestoreResponse = (postVaultsVaultIdTrashIdRestoreResponseSuccess | postVaultsVaultIdTrashIdRestoreResponseError)

export const getPostVaultsVaultIdTrashIdRestoreUrl = (vaultId: string,
    id: string,) => {




  return `/vaults/${vaultId}/trash/${id}/restore`
}

export const postVaultsVaultIdTrashIdRestore = async (vaultId: string,
    id: string, options?: RequestInit): Promise<postVaultsVaultIdTrashIdRestoreResponse> => {

  return apiFetcher<postVaultsVaultIdTrashIdRestoreResponse>(getPostVaultsVaultIdTrashIdRestoreUrl(vaultId,id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostVaultsVaultIdTrashIdRestoreMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdTrashIdRestore>>, TError,{vaultId: string;id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdTrashIdRestore>>, TError,{vaultId: string;id: string}, TContext> => {

const mutationKey = ['postVaultsVaultIdTrashIdRestore'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postVaultsVaultIdTrashIdRestore>>, {vaultId: string;id: string}> = (props) => {
          const {vaultId,id} = props ?? {};

          return  postVaultsVaultIdTrashIdRestore(vaultId,id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostVaultsVaultIdTrashIdRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof postVaultsVaultIdTrashIdRestore>>>

    export type PostVaultsVaultIdTrashIdRestoreMutationError = ErrorBody

    /**
 * @summary Restore item
 */
export const usePostVaultsVaultIdTrashIdRestore = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postVaultsVaultIdTrashIdRestore>>, TError,{vaultId: string;id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postVaultsVaultIdTrashIdRestore>>,
        TError,
        {vaultId: string;id: string},
        TContext
      > => {
      return useMutation(getPostVaultsVaultIdTrashIdRestoreMutationOptions(options), queryClient);
    }
